import json
import os
import stat
import subprocess
import tempfile
import tomllib
import unittest
from pathlib import Path
from typing import TypedDict

from solomon_harness.engine_adapters import build_engine_command
from solomon_harness.host_adapters import HOSTS, compile_adapters, inspect_capabilities
from solomon_harness.host_hooks import normalize_hook_input
from solomon_harness.install_layout import install_project
from solomon_harness.layout import HarnessPaths


SOURCE_ROOT = Path(__file__).resolve().parents[1]


class McpDocument(TypedDict, total=False):
    command: str
    args: list[str]
    env: dict[str, str]
    required: bool


class HostAdaptersTest(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        install_project(self.root, source_root=SOURCE_ROOT)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _make_tracked_legacy_generated_bridge(self, *, source_checkout: bool) -> Path:
        target = self.root / ".claude" / "agents" / "qa.md"
        target.write_text(
            "Legacy generated bridge.\n\n"
            "This file is generated by scripts/generate-integrations.py. "
            "Edit the source instead.\n",
            encoding="utf-8",
        )
        (self.root / ".agents" / "solomon" / "manifest.json").unlink()
        tracked = [target.relative_to(self.root).as_posix()]
        if source_checkout:
            package = self.root / "solomon_harness"
            package.mkdir()
            (package / "__init__.py").write_text("\n", encoding="utf-8")
            (package / "mcp_server.py").write_text("\n", encoding="utf-8")
            scripts = self.root / "scripts"
            scripts.mkdir(exist_ok=True)
            (scripts / "generate-integrations.py").write_text("\n", encoding="utf-8")
            source_agents = self.root / "agents"
            source_agents.mkdir(exist_ok=True)
            (source_agents / "AGENTS.md").write_text(
                "# Source rules\n", encoding="utf-8"
            )
            (self.root / "pyproject.toml").write_text(
                '[project]\nname = "solomon-harness"\nversion = "0.0.0"\n',
                encoding="utf-8",
            )
            tracked.extend(
                (
                    "pyproject.toml",
                    "agents/AGENTS.md",
                    "solomon_harness/__init__.py",
                    "solomon_harness/mcp_server.py",
                    "scripts/generate-integrations.py",
                )
            )
        subprocess.run(["git", "init", "-q", str(self.root)], check=True)
        subprocess.run(
            ["git", "-C", str(self.root), "add", "-f", "--", *tracked],
            check=True,
        )
        subprocess.run(
            [
                "git",
                "-C",
                str(self.root),
                "-c",
                "user.name=Solomon Test",
                "-c",
                "user.email=solomon@example.invalid",
                "commit",
                "-qm",
                "tracked generated bridge",
            ],
            check=True,
        )
        return target

    def _make_source_checkout(self) -> Path:
        """Create the smallest Git-proven source tree accepted by the compiler."""

        root = self.root / "source-checkout"
        files = {
            "pyproject.toml": (
                "[project]\n"
                'name = "solomon-harness"\n'
                'version = "0.0.0"\n'
            ),
            "solomon_harness/__init__.py": "\n",
            "solomon_harness/mcp_server.py": "\n",
            "solomon_harness/catalog/workflows/solomon-bug.md": (
                "---\n"
                "description: File a source-checkout bug.\n"
                "---\n\n"
                "# Bug\n"
            ),
            "scripts/generate-integrations.py": "\n",
            "agents/AGENTS.md": "# Source rules\n",
            "agents/qa/persona.md": "# QA persona\n",
            "agents/qa/agents/qa.md": (
                "# QA Profile\n\n"
                "Validates the harness.\n\n"
                "## Delegation cue\n\n"
                "Use this agent when runtime parity needs verification.\n"
            ),
            "agents/qa/skills/runtime.md": "# Runtime verification\n",
            ".claude/commands/solomon-bug.md": (
                "---\n"
                "description: File a source-checkout bug.\n"
                "allowed-tools: Read, Bash(uv:*)\n"
                "---\n\n"
                "# Bug\n"
            ),
        }
        for relative, content in files.items():
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        subprocess.run(["git", "init", "-q", str(root)], check=True)
        subprocess.run(["git", "-C", str(root), "add", "--all"], check=True)
        subprocess.run(
            [
                "git",
                "-C",
                str(root),
                "-c",
                "user.name=Solomon Test",
                "-c",
                "user.email=solomon@example.invalid",
                "commit",
                "-qm",
                "source fixture",
            ],
            check=True,
        )
        return root

    def _mcp_documents(self, root: Path) -> dict[str, McpDocument]:
        claude = json.loads((root / ".mcp.json").read_text(encoding="utf-8"))[
            "mcpServers"
        ]["solomon-memory"]
        agy = json.loads(
            (
                root
                / ".agents"
                / "plugins"
                / "solomon"
                / "mcp_config.json"
            ).read_text(encoding="utf-8")
        )["mcpServers"]["solomon-memory"]
        codex = tomllib.loads(
            (root / ".codex" / "config.toml").read_text(encoding="utf-8")
        )["mcp_servers"]["solomon-memory"]
        return {"claude": claude, "agy": agy, "codex": codex}

    def _hook_commands(self, root: Path) -> dict[str, str]:
        claude = json.loads(
            (root / ".claude" / "settings.json").read_text(encoding="utf-8")
        )["hooks"]["SessionStart"][0]["hooks"][0]["command"]
        agy = json.loads(
            (root / ".agents" / "hooks.json").read_text(encoding="utf-8")
        )["solomon-session-resume"]["PreInvocation"][0]["command"]
        codex = tomllib.loads(
            (root / ".codex" / "config.toml").read_text(encoding="utf-8")
        )["hooks"]["SessionStart"][0]["hooks"][0]["command"]
        return {"claude": claude, "agy": agy, "codex": codex}

    def _fake_uv(self, root: Path) -> tuple[Path, dict[str, str]]:
        fake_bin = root / "fake-bin"
        fake_bin.mkdir(exist_ok=True)
        fake_uv = fake_bin / "uv"
        fake_uv.write_text(
            "#!/bin/sh\n"
            "python3 -c 'import json, os, sys; "
            "json.dump({\"argv\": sys.argv[1:], \"cwd\": os.getcwd(), "
            "\"venv\": os.environ.get(\"UV_PROJECT_ENVIRONMENT\")}, "
            "open(os.environ[\"CAPTURE\"], \"w\"))' \"$@\"\n",
            encoding="utf-8",
        )
        fake_uv.chmod(0o755)
        environment = dict(os.environ)
        environment["PATH"] = f"{fake_bin}{os.pathsep}{environment.get('PATH', '')}"
        return fake_uv, environment

    def test_three_hosts_publish_the_same_capabilities(self) -> None:
        self.assertEqual(HOSTS, ("agy", "claude", "codex"))
        matrix = inspect_capabilities(self.root)
        self.assertEqual(set(matrix), set(HOSTS))
        expected = matrix["claude"]
        self.assertEqual(expected["capabilities"], {
            "instructions",
            "specialists",
            "workflows",
            "session_start",
            "pre_tool_guard",
            "mcp",
            "headless",
        })
        for host in HOSTS:
            self.assertEqual(matrix[host]["specialists"], expected["specialists"])
            self.assertEqual(matrix[host]["workflows"], expected["workflows"])
            self.assertEqual(matrix[host]["capabilities"], expected["capabilities"])
        self.assertEqual(len(expected["specialists"]), 28)
        self.assertEqual(len(expected["workflows"]), 11)

        self.assertEqual(matrix["claude"]["status"], "configured")
        self.assertEqual(matrix["agy"]["status"], "configured")
        self.assertEqual(matrix["codex"]["status"], "pending_trust")
        self.assertEqual(
            matrix["codex"]["capability_states"]["pre_tool_guard"],
            "pending_trust",
        )
        self.assertEqual(
            matrix["codex"]["capability_states"]["instructions"],
            "active",
        )

    def test_fresh_install_uses_native_paths_and_never_gemini(self) -> None:
        paths = HarnessPaths(self.root)
        self.assertTrue((self.root / ".claude" / "CLAUDE.md").is_file())
        self.assertTrue((self.root / ".claude" / "settings.json").is_file())
        self.assertTrue((self.root / ".agents" / "hooks.json").is_file())
        self.assertTrue(
            (
                self.root
                / ".agents"
                / "plugins"
                / "solomon"
                / "mcp_config.json"
            ).is_file()
        )
        self.assertFalse((self.root / ".agents" / "mcp_config.json").exists())
        self.assertTrue((self.root / ".agents" / "plugins" / "solomon" / "plugin.json").is_file())
        self.assertTrue((self.root / ".codex" / "config.toml").is_file())
        self.assertFalse((self.root / ".codex" / "hooks.json").exists())
        codex = tomllib.loads(
            (self.root / ".codex" / "config.toml").read_text(encoding="utf-8")
        )
        self.assertEqual(set(codex["hooks"]), {"PreToolUse", "SessionStart"})
        self.assertFalse((self.root / ".gemini").exists())
        self.assertEqual(len(list((self.root / ".claude" / "agents").glob("*.md"))), 28)
        self.assertEqual(len(list((self.root / ".codex" / "agents").glob("*.toml"))), 28)
        self.assertEqual(len(list((paths.root / ".agents" / "skills").glob("solomon-*/SKILL.md"))), 11)

    def test_bridges_are_thin_parseable_and_reference_the_core(self) -> None:
        bridge_files = [
            *sorted((self.root / ".claude" / "agents").glob("*.md")),
            *sorted((self.root / ".claude" / "skills").glob("solomon-*/SKILL.md")),
            *sorted((self.root / ".codex" / "agents").glob("*.toml")),
            *sorted((self.root / ".agents" / "skills").glob("solomon-*/SKILL.md")),
        ]
        self.assertTrue(bridge_files)
        for path in bridge_files:
            content = path.read_text(encoding="utf-8")
            self.assertLess(len(content.encode("utf-8")), 4096, path)
            self.assertIn(".agents/solomon", content, path)
            self.assertNotIn(str(SOURCE_ROOT), content, path)
            if path.suffix == ".toml":
                tomllib.loads(content)

    def test_every_specialist_bridge_keeps_its_delegation_trigger(self) -> None:
        claude = sorted((self.root / ".claude" / "agents").glob("*.md"))
        agy = sorted((self.root / ".agents" / "agents").glob("*/agent.md"))
        codex = sorted((self.root / ".codex" / "agents").glob("*.toml"))
        for path in (*claude, *agy):
            with self.subTest(path=path):
                frontmatter = path.read_text(encoding="utf-8").split("---", 2)[1]
                self.assertIn("Use this agent when", frontmatter)
        for path in codex:
            with self.subTest(path=path):
                description = tomllib.loads(path.read_text(encoding="utf-8"))[
                    "description"
                ]
                self.assertIn("Use this agent when", description)

    def test_claude_skill_reads_installed_host_metadata_only(self) -> None:
        metadata = (
            self.root
            / ".agents"
            / "solomon"
            / "host-metadata"
            / "claude"
            / "commands"
            / "solomon-bug.md"
        )
        metadata.parent.mkdir(parents=True, exist_ok=True)
        metadata.write_text(
            "---\nallowed-tools: Read, Bash(git:*)\n---\n\nHost-only metadata.\n",
            encoding="utf-8",
        )

        result = compile_adapters(self.root)

        self.assertNotIn(".claude/skills/solomon-bug/SKILL.md", result.conflicts)
        claude = (
            self.root / ".claude" / "skills" / "solomon-bug" / "SKILL.md"
        ).read_text(encoding="utf-8")
        shared = (
            self.root / ".agents" / "skills" / "solomon-bug" / "SKILL.md"
        ).read_text(encoding="utf-8")
        self.assertIn("allowed-tools: Read, Bash(git:*)", claude)
        self.assertNotIn("allowed-tools:", shared)

    def test_claude_skill_falls_back_to_source_checkout_command_metadata(self) -> None:
        installed = (
            self.root
            / ".agents"
            / "solomon"
            / "host-metadata"
            / "claude"
            / "commands"
            / "solomon-bug.md"
        )
        installed.unlink(missing_ok=True)
        legacy = self.root / ".claude" / "commands" / "solomon-bug.md"
        legacy.parent.mkdir(parents=True, exist_ok=True)
        legacy.write_text(
            "---\nallowed-tools: Read, Grep\n---\n\nSource bridge.\n",
            encoding="utf-8",
        )

        result = compile_adapters(self.root)

        self.assertNotIn(".claude/skills/solomon-bug/SKILL.md", result.conflicts)
        claude = (
            self.root / ".claude" / "skills" / "solomon-bug" / "SKILL.md"
        ).read_text(encoding="utf-8")
        self.assertIn("allowed-tools: Read, Grep", claude)

    def test_installed_specialists_do_not_pin_any_host_model(self) -> None:
        configs = sorted(
            (self.root / ".agents" / "solomon" / "agents").glob("*/.agent/config.json")
        )
        self.assertEqual(len(configs), 28)
        for path in configs:
            self.assertNotIn("models", json.loads(path.read_text(encoding="utf-8")), path)

        adapter_text = "\n".join(
            path.read_text(encoding="utf-8")
            for path in (
                self.root / ".claude" / "settings.json",
                self.root / ".agents" / "hooks.json",
                self.root / ".codex" / "config.toml",
            )
        )
        self.assertNotIn("gemini-", adapter_text)
        self.assertNotIn("--dangerously-bypass-hook-trust", adapter_text)

    def test_host_configuration_is_parseable_and_mcp_is_semantically_equal(self) -> None:
        claude = json.loads((self.root / ".mcp.json").read_text(encoding="utf-8"))[
            "mcpServers"
        ]["solomon-memory"]
        agy = json.loads(
            HarnessPaths(self.root).agy_mcp.read_text(encoding="utf-8")
        )["mcpServers"]["solomon-memory"]
        codex_text = (self.root / ".codex" / "config.toml").read_text(encoding="utf-8")
        codex = tomllib.loads(codex_text)["mcp_servers"]["solomon-memory"]
        expected = (
            "uv",
            [
                "run",
                "--frozen",
                "--project",
                ".agents/solomon",
                "python",
                "-m",
                "solomon_harness.mcp_server",
            ],
        )
        for config in (claude, agy, codex):
            self.assertEqual((config["command"], config["args"]), expected)
            self.assertEqual(
                config["env"]["UV_PROJECT_ENVIRONMENT"],
                "state/venv",
            )
        json.loads((self.root / ".claude" / "settings.json").read_text(encoding="utf-8"))
        json.loads((self.root / ".agents" / "hooks.json").read_text(encoding="utf-8"))
        tomllib.loads((self.root / ".codex" / "config.toml").read_text(encoding="utf-8"))

    def test_consumer_mcp_and_hooks_are_executable_for_every_host(self) -> None:
        _, environment = self._fake_uv(self.root)
        nested = self.root / "product" / "src"
        nested.mkdir(parents=True)

        for host, config in self._mcp_documents(self.root).items():
            capture = self.root / f"consumer-mcp-{host}.json"
            process_environment = dict(environment)
            process_environment.update(config["env"])
            process_environment["CAPTURE"] = str(capture)
            completed = subprocess.run(
                [config["command"], *config["args"]],
                cwd=self.root,
                env=process_environment,
                text=True,
                capture_output=True,
                check=False,
            )
            with self.subTest(surface="mcp", host=host):
                self.assertEqual(completed.returncode, 0, completed.stderr)
                invocation = json.loads(capture.read_text(encoding="utf-8"))
                project_index = invocation["argv"].index("--project") + 1
                project = self.root / invocation["argv"][project_index]
                self.assertEqual(
                    project.resolve(),
                    (self.root / ".agents" / "solomon").resolve(),
                )
                self.assertEqual(invocation["venv"], "state/venv")

        for host, command in self._hook_commands(self.root).items():
            capture = self.root / f"consumer-hook-{host}.json"
            process_environment = dict(environment)
            process_environment["CAPTURE"] = str(capture)
            completed = subprocess.run(
                command,
                cwd=nested,
                env=process_environment,
                shell=True,
                text=True,
                capture_output=True,
                check=False,
            )
            with self.subTest(surface="hook", host=host):
                self.assertEqual(completed.returncode, 0, completed.stderr)
                invocation = json.loads(capture.read_text(encoding="utf-8"))
                project_index = invocation["argv"].index("--project") + 1
                self.assertEqual(
                    Path(invocation["argv"][project_index]).resolve(),
                    (self.root / ".agents" / "solomon").resolve(),
                )
                self.assertEqual(
                    Path(invocation["venv"]).resolve(),
                    (
                        self.root
                        / ".agents"
                        / "solomon"
                        / "state"
                        / "venv"
                    ).resolve(),
                )

    def test_source_checkout_uses_root_project_and_is_semantically_complete(self) -> None:
        source = self._make_source_checkout()

        result = compile_adapters(source)
        matrix = inspect_capabilities(source)
        repeated = compile_adapters(source)

        self.assertFalse(result.conflicts)
        self.assertFalse(repeated.changed)
        self.assertFalse(repeated.conflicts)
        expected_capabilities = {
            "headless",
            "instructions",
            "mcp",
            "pre_tool_guard",
            "session_start",
            "specialists",
            "workflows",
        }
        for host in HOSTS:
            with self.subTest(host=host):
                self.assertEqual(matrix[host]["capabilities"], expected_capabilities)
                self.assertEqual(matrix[host]["specialists"], ("qa",))
                self.assertEqual(matrix[host]["workflows"], ("bug",))

        for host, config in self._mcp_documents(source).items():
            with self.subTest(host=host):
                self.assertEqual(config["command"], "uv")
                self.assertEqual(
                    config["args"],
                    [
                        "run",
                        "--frozen",
                        "--project",
                        ".",
                        "python",
                        "-m",
                        "solomon_harness.mcp_server",
                    ],
                )
                self.assertEqual(
                    config["env"],
                    {"UV_PROJECT_ENVIRONMENT": ".agents/solomon/state/venv"},
                )
        codex = self._mcp_documents(source)["codex"]
        self.assertIs(codex["required"], True)
        shared_skill = (
            source / ".agents" / "skills" / "solomon-bug" / "SKILL.md"
        ).read_text(encoding="utf-8")
        self.assertIn(
            "solomon_harness/catalog/workflows/solomon-bug.md", shared_skill
        )
        self.assertNotIn(".claude/commands/solomon-bug.md", shared_skill)

    def test_source_mcp_and_hooks_are_executable_for_every_host(self) -> None:
        source = self._make_source_checkout()
        compile_adapters(source)
        _, environment = self._fake_uv(source)
        nested = source / "product" / "src"
        nested.mkdir(parents=True)

        for host, config in self._mcp_documents(source).items():
            capture = source / f"mcp-{host}.json"
            process_environment = dict(environment)
            process_environment.update(config["env"])
            process_environment["CAPTURE"] = str(capture)
            completed = subprocess.run(
                [config["command"], *config["args"]],
                cwd=source,
                env=process_environment,
                text=True,
                capture_output=True,
                check=False,
            )
            with self.subTest(surface="mcp", host=host):
                self.assertEqual(completed.returncode, 0, completed.stderr)
                invocation = json.loads(capture.read_text(encoding="utf-8"))
                project_index = invocation["argv"].index("--project") + 1
                self.assertEqual(invocation["argv"][project_index], ".")
                self.assertEqual(
                    invocation["venv"], ".agents/solomon/state/venv"
                )

        for host, command in self._hook_commands(source).items():
            capture = source / f"hook-{host}.json"
            process_environment = dict(environment)
            process_environment["CAPTURE"] = str(capture)
            completed = subprocess.run(
                command,
                cwd=nested,
                env=process_environment,
                shell=True,
                text=True,
                capture_output=True,
                check=False,
            )
            with self.subTest(surface="hook", host=host):
                self.assertEqual(completed.returncode, 0, completed.stderr)
                invocation = json.loads(capture.read_text(encoding="utf-8"))
                project_index = invocation["argv"].index("--project") + 1
                self.assertEqual(
                    Path(invocation["argv"][project_index]).resolve(),
                    source.resolve(),
                )
                self.assertEqual(
                    Path(invocation["venv"]).resolve(),
                    (source / ".agents" / "solomon" / "state" / "venv").resolve(),
                )

    def test_source_hook_falls_back_to_ancestor_without_git_metadata(self) -> None:
        source = self._make_source_checkout()
        compile_adapters(source)
        command = self._hook_commands(source)["codex"]
        (source / ".git").rename(source / ".git-disabled")
        _, environment = self._fake_uv(source)
        capture = source / "source-fallback.json"
        environment["CAPTURE"] = str(capture)
        nested = source / "product" / "src"
        nested.mkdir(parents=True)

        completed = subprocess.run(
            command,
            cwd=nested,
            env=environment,
            shell=True,
            text=True,
            capture_output=True,
            check=False,
        )

        self.assertEqual(completed.returncode, 0, completed.stderr)
        invocation = json.loads(capture.read_text(encoding="utf-8"))
        project_index = invocation["argv"].index("--project") + 1
        self.assertEqual(
            Path(invocation["argv"][project_index]).resolve(), source.resolve()
        )

    def test_clean_tracked_source_configs_upgrade_from_consumer_runtime(self) -> None:
        source = self._make_source_checkout()
        compile_adapters(source)
        runtime_configs = (
            ".claude/settings.json",
            ".agents/hooks.json",
            ".mcp.json",
            ".agents/plugins/solomon/mcp_config.json",
            ".codex/config.toml",
        )
        for relative in runtime_configs:
            target = source / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes((self.root / relative).read_bytes())
        subprocess.run(
            ["git", "-C", str(source), "add", "--", *runtime_configs], check=True
        )
        subprocess.run(
            [
                "git",
                "-C",
                str(source),
                "-c",
                "user.name=Solomon Test",
                "-c",
                "user.email=solomon@example.invalid",
                "commit",
                "-qm",
                "tracked legacy source adapters",
            ],
            check=True,
        )

        result = compile_adapters(source)

        self.assertFalse(set(runtime_configs) & set(result.conflicts))
        for config in self._mcp_documents(source).values():
            self.assertEqual(config["args"][3], ".")
            self.assertEqual(
                config["env"]["UV_PROJECT_ENVIRONMENT"],
                ".agents/solomon/state/venv",
            )
        for command in self._hook_commands(source).values():
            self.assertIn('uv run --frozen --project "$SOLOMON_ROOT"', command)

    def test_source_runtime_state_is_git_ignored(self) -> None:
        ignored = subprocess.run(
            [
                "git",
                "-C",
                str(SOURCE_ROOT),
                "check-ignore",
                "-q",
                "--",
                ".agents/solomon/state/runtime-probe",
            ],
            check=False,
        )

        self.assertEqual(ignored.returncode, 0)

    def test_unproven_source_shape_keeps_consumer_runtime_layout(self) -> None:
        source = self._make_source_checkout()
        (source / ".git").rename(source / ".git-disabled")

        compile_adapters(source)

        for host, config in self._mcp_documents(source).items():
            with self.subTest(host=host):
                self.assertEqual(config["args"][3], ".agents/solomon")
                self.assertEqual(
                    config["env"], {"UV_PROJECT_ENVIRONMENT": "state/venv"}
                )
        self.assertIs(self._mcp_documents(source)["codex"]["required"], False)

    def test_required_codex_mcp_is_unavailable_when_source_command_is_wrong(self) -> None:
        source = self._make_source_checkout()
        compile_adapters(source)
        config_path = source / ".codex" / "config.toml"
        config_path.write_text(
            config_path.read_text(encoding="utf-8").replace(
                '"--project", "."',
                '"--project", ".agents/solomon"',
            ),
            encoding="utf-8",
        )

        matrix = inspect_capabilities(source)

        self.assertIs(
            tomllib.loads(config_path.read_text(encoding="utf-8"))["mcp_servers"][
                "solomon-memory"
            ]["required"],
            True,
        )
        self.assertEqual(matrix["codex"]["capability_states"]["mcp"], "unavailable")

    def test_compile_is_idempotent(self) -> None:
        before = {
            p.relative_to(self.root).as_posix(): p.read_bytes()
            for p in self.root.rglob("*")
            if p.is_file()
        }
        first = compile_adapters(self.root)
        second = compile_adapters(self.root)
        after = {
            p.relative_to(self.root).as_posix(): p.read_bytes()
            for p in self.root.rglob("*")
            if p.is_file()
        }
        self.assertFalse(first.changed)
        self.assertFalse(second.changed)
        self.assertEqual(before, after)

    def test_compile_preserves_symlinked_adapter_target(self) -> None:
        outside = self.root.parent / "outside-host-adapter.json"
        outside.write_text('{"safe": true}\n', encoding="utf-8")
        target = self.root / ".mcp.json"
        target.unlink()
        target.symlink_to(outside)
        try:
            result = compile_adapters(self.root)
            self.assertIn(".mcp.json", result.conflicts)
            self.assertEqual(outside.read_text(encoding="utf-8"), '{"safe": true}\n')
        finally:
            target.unlink(missing_ok=True)
            outside.unlink(missing_ok=True)

    def test_generated_marker_is_not_proof_that_a_modified_file_is_owned(self) -> None:
        target = self.root / ".claude" / "agents" / "qa.md"
        original = target.read_text(encoding="utf-8")
        modified = original + "\nUser-owned note that must survive.\n"
        target.write_text(modified, encoding="utf-8")

        result = compile_adapters(self.root)

        self.assertIn(".claude/agents/qa.md", result.conflicts)
        self.assertEqual(target.read_text(encoding="utf-8"), modified)

    def test_mode_only_drift_conflicts_for_whole_and_merged_adapters(self) -> None:
        whole = self.root / ".claude" / "agents" / "qa.md"
        merged = self.root / ".claude" / "settings.json"
        os.chmod(whole, stat.S_IMODE(whole.stat().st_mode) | 0o111)
        os.chmod(merged, 0o600)
        before = {
            path: (path.read_bytes(), stat.S_IMODE(path.stat().st_mode))
            for path in (whole, merged)
        }

        result = compile_adapters(self.root)

        self.assertTrue(
            {".claude/agents/qa.md", ".claude/settings.json"}
            <= set(result.conflicts)
        )
        for path, expected in before.items():
            with self.subTest(path=path):
                self.assertEqual(
                    (path.read_bytes(), stat.S_IMODE(path.stat().st_mode)),
                    expected,
                )

    def test_clean_tracked_source_bridge_can_be_upgraded_without_manifest(self) -> None:
        target = self._make_tracked_legacy_generated_bridge(source_checkout=True)

        result = compile_adapters(self.root)

        self.assertNotIn(".claude/agents/qa.md", result.conflicts)
        self.assertIn(
            "Generated by solomon-harness; edit the source under .agents/solomon.",
            target.read_text(encoding="utf-8"),
        )

    def test_modified_tracked_source_bridge_is_not_overwritten(self) -> None:
        target = self._make_tracked_legacy_generated_bridge(source_checkout=True)
        modified = target.read_text(encoding="utf-8") + "Consumer edit.\n"
        target.write_text(modified, encoding="utf-8")

        result = compile_adapters(self.root)

        self.assertIn(".claude/agents/qa.md", result.conflicts)
        self.assertEqual(target.read_text(encoding="utf-8"), modified)

    def test_clean_tracked_consumer_bridge_is_not_overwritten_without_manifest(self) -> None:
        target = self._make_tracked_legacy_generated_bridge(source_checkout=False)
        original = target.read_text(encoding="utf-8")

        result = compile_adapters(self.root)

        self.assertIn(".claude/agents/qa.md", result.conflicts)
        self.assertEqual(target.read_text(encoding="utf-8"), original)

    def test_removing_a_managed_hook_is_a_conflict_for_every_host(self) -> None:
        claude_path = self.root / ".claude" / "settings.json"
        claude = json.loads(claude_path.read_text(encoding="utf-8"))
        claude["hooks"].pop("SessionStart")
        claude_path.write_text(json.dumps(claude), encoding="utf-8")

        agy_path = self.root / ".agents" / "hooks.json"
        agy = json.loads(agy_path.read_text(encoding="utf-8"))
        agy.pop("solomon-loop-guard")
        agy_path.write_text(json.dumps(agy), encoding="utf-8")

        codex_path = self.root / ".codex" / "config.toml"
        codex_text = codex_path.read_text(encoding="utf-8")
        before, remainder = codex_text.split("[[hooks.PreToolUse]]", 1)
        _, after = remainder.split("[[hooks.SessionStart]]", 1)
        codex_path.write_text(
            before + "[[hooks.SessionStart]]" + after,
            encoding="utf-8",
        )

        result = compile_adapters(self.root)

        self.assertTrue(
            {
                ".claude/settings.json",
                ".agents/hooks.json",
                ".codex/config.toml",
            }
            <= set(result.conflicts)
        )
        self.assertNotIn(
            "SessionStart",
            json.loads(claude_path.read_text(encoding="utf-8"))["hooks"],
        )
        self.assertNotIn(
            "solomon-loop-guard",
            json.loads(agy_path.read_text(encoding="utf-8")),
        )
        self.assertNotIn(
            "hooks.PreToolUse",
            codex_path.read_text(encoding="utf-8"),
        )

    def test_unrelated_native_configuration_is_preserved_byte_for_byte(self) -> None:
        json_paths = (
            self.root / ".claude" / "settings.json",
            self.root / ".agents" / "hooks.json",
            self.root / ".mcp.json",
            HarnessPaths(self.root).agy_mcp,
        )
        before: dict[Path, bytes] = {}
        for path in json_paths:
            document = json.loads(path.read_text(encoding="utf-8"))
            document["consumer-owned"] = {"keep": True}
            path.write_text(
                json.dumps(document, ensure_ascii=False, indent=4) + "\n",
                encoding="utf-8",
            )
            before[path] = path.read_bytes()

        codex_config = self.root / ".codex" / "config.toml"
        with codex_config.open("a", encoding="utf-8") as stream:
            stream.write('\n[consumer]\nkeep = true\n')
        before[codex_config] = codex_config.read_bytes()

        result = compile_adapters(self.root)

        self.assertFalse(set(before) & {self.root / item for item in result.conflicts})
        for path, expected in before.items():
            with self.subTest(path=path):
                self.assertEqual(path.read_bytes(), expected)

    def test_modified_managed_mcp_node_is_preserved_for_every_host(self) -> None:
        claude_path = self.root / ".mcp.json"
        claude = json.loads(claude_path.read_text(encoding="utf-8"))
        claude["mcpServers"]["solomon-memory"]["command"] = "consumer-command"
        claude_path.write_text(json.dumps(claude), encoding="utf-8")

        agy_path = HarnessPaths(self.root).agy_mcp
        agy = json.loads(agy_path.read_text(encoding="utf-8"))
        agy["mcpServers"]["solomon-memory"].pop("env")
        agy_path.write_text(json.dumps(agy), encoding="utf-8")

        codex_path = self.root / ".codex" / "config.toml"
        codex_text = codex_path.read_text(encoding="utf-8").replace(
            'UV_PROJECT_ENVIRONMENT = "state/venv"',
            'UV_PROJECT_ENVIRONMENT = "consumer-venv"',
        )
        codex_path.write_text(codex_text, encoding="utf-8")
        before = {path: path.read_bytes() for path in (claude_path, agy_path, codex_path)}

        result = compile_adapters(self.root)

        self.assertTrue(
            {
                ".mcp.json",
                ".agents/plugins/solomon/mcp_config.json",
                ".codex/config.toml",
            }
            <= set(result.conflicts)
        )
        for path, expected in before.items():
            with self.subTest(path=path):
                self.assertEqual(path.read_bytes(), expected)

    def test_duplicate_managed_markers_fail_closed(self) -> None:
        instructions = self.root / "AGENTS.md"
        instructions.write_text(
            instructions.read_text(encoding="utf-8")
            + "\n<!-- solomon-harness:start -->\nduplicate\n"
            + "<!-- solomon-harness:end -->\n",
            encoding="utf-8",
        )
        codex_config = self.root / ".codex" / "config.toml"
        codex_config.write_text(
            codex_config.read_text(encoding="utf-8")
            + "\n# >>> solomon-harness managed adapter >>>\nduplicate = true\n"
            + "# <<< solomon-harness managed adapter <<<\n",
            encoding="utf-8",
        )
        before = {
            instructions: instructions.read_bytes(),
            codex_config: codex_config.read_bytes(),
        }

        result = compile_adapters(self.root)

        self.assertTrue({"AGENTS.md", ".codex/config.toml"} <= set(result.conflicts))
        for path, expected in before.items():
            self.assertEqual(path.read_bytes(), expected)

    def test_modified_managed_instruction_block_is_preserved_as_a_conflict(self) -> None:
        target = self.root / "AGENTS.md"
        modified = target.read_text(encoding="utf-8").replace(
            "The Solomon rules are in `.agents/solomon/AGENTS.md`.",
            "Consumer-owned instruction.",
        )
        target.write_text(modified, encoding="utf-8")

        result = compile_adapters(self.root)

        self.assertIn("AGENTS.md", result.conflicts)
        self.assertEqual(target.read_text(encoding="utf-8"), modified)

    def test_hook_commands_resolve_git_root_and_keep_runtime_venv_in_state(self) -> None:
        claude_handler = json.loads(
            (self.root / ".claude" / "settings.json").read_text(encoding="utf-8")
        )["hooks"]["SessionStart"][0]["hooks"][0]
        agy_handler = json.loads(
            (self.root / ".agents" / "hooks.json").read_text(encoding="utf-8")
        )["solomon-session-resume"]["PreInvocation"][0]
        codex_handler = tomllib.loads(
            (self.root / ".codex" / "config.toml").read_text(encoding="utf-8")
        )["hooks"]["SessionStart"][0]["hooks"][0]
        documents = {
            "claude": claude_handler["command"],
            "agy": agy_handler["command"],
            "codex": codex_handler["command"],
        }
        for host, command in documents.items():
            with self.subTest(host=host):
                self.assertIn("git rev-parse --show-toplevel", command)
                self.assertIn(".agents/solomon/pyproject.toml", command)
                self.assertIn("UV_PROJECT_ENVIRONMENT", command)
                self.assertIn(".agents/solomon/state/venv", command)
                self.assertIn('--project "$SOLOMON_ROOT/.agents/solomon"', command)

        windows_command = codex_handler["commandWindows"]
        self.assertIn("git rev-parse --show-toplevel", windows_command)
        self.assertIn(".agents\\solomon\\state\\venv", windows_command)
        self.assertIn('uv run --frozen --project "%R\\.agents\\solomon"', windows_command)
        self.assertNotIn("commandWindows", claude_handler)
        self.assertNotIn("commandWindows", agy_handler)

        subprocess.run(["git", "init", "-q", str(self.root)], check=True)
        nested = self.root / "product" / "src"
        nested.mkdir(parents=True)
        fake_bin = self.root / "fake-bin"
        fake_bin.mkdir()
        capture = self.root / "uv-capture.json"
        fake_uv = fake_bin / "uv"
        fake_uv.write_text(
            "#!/bin/sh\n"
            "python3 -c 'import json, os, sys; "
            "json.dump({\"argv\": sys.argv[1:], \"venv\": "
            "os.environ.get(\"UV_PROJECT_ENVIRONMENT\")}, "
            "open(os.environ[\"CAPTURE\"], \"w\"))' \"$@\"\n",
            encoding="utf-8",
        )
        fake_uv.chmod(0o755)
        environment = dict(os.environ)
        environment["CAPTURE"] = str(capture)
        environment["PATH"] = f"{fake_bin}{os.pathsep}{environment.get('PATH', '')}"

        completed = subprocess.run(
            documents["codex"],
            cwd=nested,
            env=environment,
            shell=True,
            text=True,
            capture_output=True,
            check=False,
        )

        self.assertEqual(completed.returncode, 0, completed.stderr)
        invocation = json.loads(capture.read_text(encoding="utf-8"))
        self.assertEqual(
            Path(invocation["venv"]).resolve(),
            (self.root / ".agents" / "solomon" / "state" / "venv").resolve(),
        )
        project_index = invocation["argv"].index("--project") + 1
        self.assertEqual(
            Path(invocation["argv"][project_index]).resolve(),
            (self.root / ".agents" / "solomon").resolve(),
        )

    def test_hook_command_finds_install_ancestor_without_a_git_repository(self) -> None:
        command = json.loads(
            (self.root / ".claude" / "settings.json").read_text(encoding="utf-8")
        )["hooks"]["SessionStart"][0]["hooks"][0]["command"]
        nested = self.root / "consumer" / "package" / "src"
        nested.mkdir(parents=True)
        fake_bin = self.root / "fake-bin"
        fake_bin.mkdir()
        capture = self.root / "non-git-uv-capture.json"
        fake_uv = fake_bin / "uv"
        fake_uv.write_text(
            "#!/bin/sh\n"
            "python3 -c 'import json, os, sys; "
            "json.dump({\"argv\": sys.argv[1:], \"venv\": "
            "os.environ.get(\"UV_PROJECT_ENVIRONMENT\")}, "
            "open(os.environ[\"CAPTURE\"], \"w\"))' \"$@\"\n",
            encoding="utf-8",
        )
        fake_uv.chmod(0o755)
        environment = dict(os.environ)
        environment["CAPTURE"] = str(capture)
        environment["PATH"] = f"{fake_bin}{os.pathsep}{environment.get('PATH', '')}"

        completed = subprocess.run(
            command,
            cwd=nested,
            env=environment,
            shell=True,
            text=True,
            capture_output=True,
            check=False,
        )

        self.assertEqual(completed.returncode, 0, completed.stderr)
        invocation = json.loads(capture.read_text(encoding="utf-8"))
        self.assertEqual(
            Path(invocation["venv"]).resolve(),
            (self.root / ".agents" / "solomon" / "state" / "venv").resolve(),
        )
        project_index = invocation["argv"].index("--project") + 1
        self.assertEqual(
            Path(invocation["argv"][project_index]).resolve(),
            (self.root / ".agents" / "solomon").resolve(),
        )

    def test_capability_inspection_rejects_malformed_native_configuration(self) -> None:
        codex_config = self.root / ".codex" / "config.toml"
        codex_text = codex_config.read_text(encoding="utf-8")
        prefix, managed = codex_text.split(
            "# >>> solomon-harness managed adapter >>>", 1
        )
        _, mcp = managed.split("[mcp_servers.solomon-memory]", 1)
        codex_config.write_text(
            prefix
            + "# >>> solomon-harness managed adapter >>>\n"
            + "[mcp_servers.solomon-memory]"
            + mcp,
            encoding="utf-8",
        )
        (self.root / ".codex" / "agents" / "qa.toml").unlink()
        HarnessPaths(self.root).agy_mcp.write_text(
            json.dumps({"mcpServers": {"solomon-memory": {"command": "other"}}}),
            encoding="utf-8",
        )

        matrix = inspect_capabilities(self.root)

        self.assertNotIn("session_start", matrix["codex"]["capabilities"])
        self.assertNotIn("pre_tool_guard", matrix["codex"]["capabilities"])
        self.assertEqual(
            matrix["codex"]["capability_states"]["session_start"],
            "unavailable",
        )
        self.assertNotIn("specialists", matrix["codex"]["capabilities"])
        self.assertEqual(
            matrix["codex"]["capability_states"]["specialists"],
            "unavailable",
        )
        self.assertNotIn("mcp", matrix["agy"]["capabilities"])
        self.assertEqual(matrix["agy"]["capability_states"]["mcp"], "unavailable")

    def test_engine_commands_are_native_and_do_not_bypass_hook_trust(self) -> None:
        self.assertEqual(build_engine_command("claude", self.root), ["claude", "-p"])
        agy = build_engine_command("agy", self.root)
        self.assertEqual(agy[:3], ["agy", "-p", "-"])
        self.assertNotIn("-o", agy)
        codex = build_engine_command("codex", self.root)
        self.assertEqual(codex[:4], ["codex", "exec", "--sandbox", "workspace-write"])
        self.assertEqual(codex[-1], "-")
        self.assertNotIn("--dangerously-bypass-hook-trust", codex)

    def test_hook_payloads_normalize_to_the_same_shell_contract(self) -> None:
        claude = normalize_hook_input(
            "claude", {"session_id": "s", "tool_name": "Bash", "tool_input": {"command": "git push"}}
        )
        codex = normalize_hook_input(
            "codex", {"session_id": "s", "tool_name": "Bash", "tool_input": {"command": "git push"}}
        )
        agy = normalize_hook_input(
            "agy", {"conversationId": "s", "toolCall": {"name": "run_command", "args": {"CommandLine": "git push"}}}
        )
        self.assertEqual((claude.tool_kind, claude.command), ("shell", "git push"))
        self.assertEqual((codex.tool_kind, codex.command), ("shell", "git push"))
        self.assertEqual((agy.tool_kind, agy.command), ("shell", "git push"))
        self.assertEqual({claude.session_id, codex.session_id, agy.session_id}, {"s"})


if __name__ == "__main__":
    unittest.main()
