#!/usr/bin/env python3
"""Compatibility entrypoint for the neutral three-host adapter compiler.

The compiler reads through ``HarnessPaths``: installed projects use the catalog
below ``.agents/solomon`` and this source repository may use the legacy source
locations for one migration window. It never generates legacy ``.gemini``
artifacts. Run from the repository root:

    python scripts/generate-integrations.py
"""

import os
import sys


def discover_agents(agents_dir: str):
    """Returns sorted agent names: subdirectories with an agents/<name>.md role file."""
    names = []
    for item in sorted(os.listdir(agents_dir)):
        role = os.path.join(agents_dir, item, "agents", f"{item}.md")
        if os.path.isfile(role):
            names.append(item)
    return names


def role_description(role_path: str, agent_name: str) -> str:
    """Builds the subagent description from the role file: its opening line
    (what the agent does) plus the first line of the `## Delegation cue`
    section (when to delegate to it), so generated subagents carry a trigger
    condition, not just a role label."""
    one_liner = ""
    cue = ""
    in_cue = False
    try:
        with open(role_path, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if stripped.startswith("## "):
                    in_cue = stripped.lower() == "## delegation cue"
                    continue
                if not stripped or stripped.startswith("#"):
                    continue
                if in_cue:
                    cue = stripped
                    break
                if not one_liner:
                    one_liner = stripped
    except OSError:
        pass
    if one_liner and cue:
        return f"{one_liner} {cue}"
    return one_liner or f"The {agent_name} specialist for solomon-harness."


def yaml_quote(value: str) -> str:
    """Render a single-line string as a double-quoted YAML scalar.

    Descriptions are natural-language sentences, so unquoted colons or hashes
    would break the generated frontmatter for any strict YAML consumer.
    """
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def subagent_markdown(agent_name: str, description: str) -> str:
    return (
        f"---\n"
        f"name: {agent_name}\n"
        f"description: {yaml_quote(description)}\n"
        f"---\n\n"
        f"You are the {agent_name} specialist agent for solomon-harness.\n\n"
        f"Your role is defined in agents/{agent_name}/agents/{agent_name}.md and your "
        f"persona in agents/{agent_name}/persona.md. Your skills are in "
        f"agents/{agent_name}/skills/. The shared project rules are in agents/AGENTS.md. "
        f"Read those files first, then act strictly within them.\n\n"
        f"Always follow agents/AGENTS.md: strict TDD, SOLID, design contracts, and the "
        f"humanizer rules (no emojis, no AI cliches). When relevant, persist decisions "
        f"and handoffs to the project memory described in agents/AGENTS.md.\n\n"
        f"This file is generated by scripts/generate-integrations.py. Edit the source "
        f"under agents/{agent_name}/, not this file.\n"
    )


def _parse_command_file(path: str):
    """Return (description, body) for a Claude Code command markdown file."""
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    description = ""
    body = text
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) == 3:
            front, body = parts[1], parts[2]
            for line in front.splitlines():
                if line.strip().lower().startswith("description:"):
                    description = line.split(":", 1)[1].strip()
                    break
    return description, body.strip()


def gemini_command_toml(description: str, body: str) -> str:
    """Render a Gemini CLI custom command (TOML) from a Claude command body.

    Claude's $ARGUMENTS becomes Gemini's {{args}}, and the Claude-specific
    mcp__solomon-memory__ tool prefix is dropped so the prompt is portable.
    """
    prompt = body.replace("$ARGUMENTS", "{{args}}").replace("mcp__solomon-memory__", "")
    desc = description.replace("\\", "\\\\").replace('"', '\\"')
    # Use a TOML multi-line literal string so the prompt needs no escaping.
    return f'description = "{desc}"\n\nprompt = \'\'\'\n{prompt}\n\'\'\'\n'


def generate_gemini_commands(workspace_root: str) -> int:
    """Deprecated compatibility shim; current AGY discovers ``.agents``."""
    del workspace_root
    return 0


def generate(workspace_root: str) -> int:
    """Delegate generation to the canonical Claude, AGY, and Codex compiler."""
    from solomon_harness.host_adapters import compile_adapters

    try:
        result = compile_adapters(workspace_root)
    except (FileNotFoundError, OSError, ValueError) as exc:
        print(f"Error: adapter compilation failed ({exc})", file=sys.stderr)
        return 1
    if result.conflicts:
        print(
            "Error: adapter conflicts were preserved: " + ", ".join(result.conflicts),
            file=sys.stderr,
        )
        return 1
    print(f"Compiled {len(result.managed_paths)} Claude, AGY, and Codex adapter paths.")
    return 0


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(script_dir, ".."))
    sys.exit(generate(root))
