#!/usr/bin/env python3
"""Generate tool-specific agent entrypoints from the central source in agents/.

Right now this emits one Claude Code subagent (.claude/agents/<name>.md) per
specialist agent. Each subagent is thin: it points back to that agent's
definition under agents/<name>/ and to the shared rules in agents/AGENTS.md, so
the agent content is never duplicated. Run from the repository root:

    python scripts/generate-integrations.py
"""

import os
import sys


def discover_agents(agents_dir: str):
    """Returns sorted agent names: subdirectories with an agents/<name>.md role file."""
    names = []
    for item in sorted(os.listdir(agents_dir)):
        role = os.path.join(agents_dir, item, "agents", f"{item}.md")
        if os.path.isfile(role):
            names.append(item)
    return names


def role_description(role_path: str, agent_name: str) -> str:
    """Uses the first non-heading, non-empty line of the role file as a one-line
    description so the subagent description tracks the role definition."""
    try:
        with open(role_path, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if stripped and not stripped.startswith("#"):
                    return stripped
    except OSError:
        pass
    return f"The {agent_name} specialist for solomon-harness."


def subagent_markdown(agent_name: str, description: str) -> str:
    return (
        f"---\n"
        f"name: {agent_name}\n"
        f"description: {description}\n"
        f"---\n\n"
        f"You are the {agent_name} specialist agent for solomon-harness.\n\n"
        f"Your role is defined in agents/{agent_name}/agents/{agent_name}.md and your "
        f"persona in agents/{agent_name}/persona.md. Your skills are in "
        f"agents/{agent_name}/skills/. The shared project rules are in agents/AGENTS.md. "
        f"Read those files first, then act strictly within them.\n\n"
        f"Always follow agents/AGENTS.md: strict TDD, SOLID, design contracts, and the "
        f"humanizer rules (no emojis, no AI cliches). When relevant, persist decisions "
        f"and handoffs to the project memory described in agents/AGENTS.md.\n\n"
        f"This file is generated by scripts/generate-integrations.py. Edit the source "
        f"under agents/{agent_name}/, not this file.\n"
    )


def generate(workspace_root: str) -> int:
    agents_dir = os.path.join(workspace_root, "agents")
    if not os.path.isdir(agents_dir):
        print(f"Error: agents directory not found at {agents_dir}", file=sys.stderr)
        return 1

    out_dir = os.path.join(workspace_root, ".claude", "agents")
    os.makedirs(out_dir, exist_ok=True)

    names = discover_agents(agents_dir)
    for name in names:
        role = os.path.join(agents_dir, name, "agents", f"{name}.md")
        description = role_description(role, name)
        with open(os.path.join(out_dir, f"{name}.md"), "w", encoding="utf-8") as f:
            f.write(subagent_markdown(name, description))

    print(f"Generated {len(names)} Claude Code subagents in {out_dir}: {', '.join(names)}")
    return 0


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(script_dir, ".."))
    sys.exit(generate(root))
