"""Compile agent harnesses from source into a separate build directory.

The agent tree under ``agents/<name>/`` is SOURCE and is owned by the author:
``persona.md``, ``.agent/config.json``, ``skills/`` and the role profile
``agents/<name>/agents/<name>.md`` are hand-maintained (the profile's
"Active Skills" section is generated by ``scripts/document-skills.py``).

Compilation never mutates that source. It reads the source, injects the
configured architecture/observability/security pattern blocks, and writes a
single composed instruction file per agent to ``build/agents/<name>/<name>.md``.
``build/`` is gitignored, so source and build output stay cleanly separated and
recompiling can never overwrite a hand-authored persona or config.
"""

import os
import sys
import json
import shutil
import logging

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
logger = logging.getLogger("harness_compiler")

# Marker that separates the composed source from the appended pattern blocks in
# the build artifact. Kept so the build file is easy to diff and regenerate.
MARKER = "<!-- BEST_PRACTICES_APPENDED_START -->"

# Which agents receive which dynamic pattern blocks.
ARCHITECTURE_AGENTS = {"software_architect", "software_engineer", "qa", "sre"}
OBSERVABILITY_AGENTS = {"observability", "software_engineer", "sre"}
SECURITY_AGENTS = {"security", "software_engineer", "qa", "sre"}


def _read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _write_text(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _resolve_template_dirs(workspace_root: str) -> tuple:
    """Resolve the harness templates and pattern dirs, preferring local overrides."""
    package_dir = os.path.dirname(os.path.abspath(__file__))

    local_templates = os.path.join(workspace_root, "templates", "harness")
    bundled_templates = os.path.join(package_dir, "templates", "harness")
    templates_dir = local_templates if os.path.isdir(local_templates) else bundled_templates

    local_patterns = os.path.join(workspace_root, "templates", "patterns")
    bundled_patterns = os.path.join(package_dir, "templates", "patterns")
    patterns_dir = local_patterns if os.path.isdir(local_patterns) else bundled_patterns

    return templates_dir, patterns_dir


def _load_pattern_settings(workspace_root: str) -> tuple:
    """Read architecture/observability/security pattern selections from global config."""
    config_path = os.path.join(workspace_root, ".agent", "config.json")
    if not os.path.isfile(config_path):
        return None, None, None
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        logger.info("Loaded dynamic pattern settings from global configuration.")
        return (
            data.get("architecture_pattern"),
            data.get("observability_pattern"),
            data.get("security_pattern"),
        )
    except Exception as exc:
        logger.warning(f"Failed to read global configuration at {config_path}: {exc}")
        return None, None, None


def _discover_agents(agents_dir: str) -> list:
    """Discover agent names from flat ``<name>.md`` files or nested role profiles."""
    names = set()
    for item in os.listdir(agents_dir):
        item_path = os.path.join(agents_dir, item)
        if os.path.isfile(item_path) and item.endswith(".md") and item != "AGENTS.md":
            names.add(item[:-3])
        elif os.path.isdir(item_path):
            nested = os.path.join(item_path, "agents", f"{item}.md")
            if os.path.isfile(nested):
                names.add(item)
    return sorted(names)


def _read_source_profile(agents_dir: str, agent_name: str) -> str:
    """Return the pattern-free source profile for an agent.

    Any previously appended pattern block (older builds wrote it back into the
    source) is stripped defensively so the build artifact is regenerated cleanly.
    """
    flat = os.path.join(agents_dir, f"{agent_name}.md")
    nested = os.path.join(agents_dir, agent_name, "agents", f"{agent_name}.md")
    path = flat if os.path.isfile(flat) else nested if os.path.isfile(nested) else None
    if path is None:
        logger.error(f"No source markdown found for agent: {agent_name}")
        sys.exit(1)
    content = _read_text(path)
    if MARKER in content:
        content = content.split(MARKER)[0]
    return content.rstrip()


def _pattern_block(patterns_dir: str, category: str, pattern_name: str) -> str:
    """Read a single pattern file, guarding against path traversal."""
    clean = os.path.basename(str(pattern_name))
    if clean != pattern_name:
        logger.error(f"Invalid {category} pattern name: {pattern_name}")
        sys.exit(1)
    path = os.path.join(patterns_dir, category, f"{pattern_name}.md")
    if not os.path.isfile(path):
        logger.error(f"{category} pattern file not found at: {path}")
        sys.exit(1)
    return _read_text(path).strip()


def _build_pattern_blocks(agent_name, patterns_dir, arch, obs, sec) -> list:
    """Collect the pattern blocks that apply to one agent, in a stable order."""
    blocks = []
    if agent_name in ARCHITECTURE_AGENTS and arch and str(arch).lower() != "none":
        blocks.append(_pattern_block(patterns_dir, "architecture", arch))
        logger.info(f"Applying architecture pattern '{arch}' to {agent_name}...")
    if agent_name in OBSERVABILITY_AGENTS and obs == "opentelemetry":
        blocks.append(_pattern_block(patterns_dir, "observability", "opentelemetry"))
        logger.info(f"Applying observability pattern 'opentelemetry' to {agent_name}...")
    if agent_name in SECURITY_AGENTS and sec == "secure_dev":
        blocks.append(_pattern_block(patterns_dir, "security", "secure_dev"))
        logger.info(f"Applying security pattern 'secure_dev' to {agent_name}...")
    return blocks


def _scaffold_missing(agent_dir: str, agent_name: str, templates_dir: str) -> None:
    """Create the entrypoint and config ONLY when absent. Never overwrite source.

    This is what keeps recompiling non-destructive: a hand-authored persona.md or
    .agent/config.json is left untouched; only genuinely missing scaffolding is
    filled in from the template.
    """
    os.makedirs(agent_dir, exist_ok=True)

    main_src = os.path.join(templates_dir, "main.py")
    main_dst = os.path.join(agent_dir, "main.py")
    if os.path.isfile(main_src) and not os.path.isfile(main_dst):
        shutil.copy2(main_src, main_dst)
        logger.info(f"Scaffolded missing main.py for {agent_name}.")

    config_src = os.path.join(templates_dir, ".agent", "config.json")
    config_dst = os.path.join(agent_dir, ".agent", "config.json")
    if os.path.isfile(config_src) and not os.path.isfile(config_dst):
        content = _read_text(config_src).replace("{{AGENT_NAME}}", agent_name)
        _write_text(config_dst, content)
        logger.info(f"Scaffolded missing .agent/config.json for {agent_name}.")


def compile_harnesses(workspace_root: str) -> None:
    """Compile every discovered agent into ``build/agents/<name>/<name>.md``."""
    agents_dir = os.path.join(workspace_root, "agents")
    if not os.path.isdir(agents_dir):
        logger.error(f"Agents root directory not found at: {agents_dir}")
        sys.exit(1)

    global_agents_md = os.path.join(agents_dir, "AGENTS.md")
    if not os.path.isfile(global_agents_md):
        logger.error(f"Global AGENTS.md rules file not found at: {global_agents_md}")
        sys.exit(1)

    templates_dir, patterns_dir = _resolve_template_dirs(workspace_root)
    global_rules = _read_text(global_agents_md).rstrip()
    arch, obs, sec = _load_pattern_settings(workspace_root)

    logger.info("Scanning for active agent specialists...")
    agent_names = _discover_agents(agents_dir)
    logger.info(f"Discovered {len(agent_names)} agents: {', '.join(agent_names)}")

    build_root = os.path.join(workspace_root, "build", "agents")

    for agent_name in agent_names:
        logger.info(f"Compiling harness for agent: {agent_name}")
        agent_dir = os.path.join(agents_dir, agent_name)

        # Fill in only genuinely missing scaffolding; never touch source files.
        _scaffold_missing(agent_dir, agent_name, templates_dir)

        profile = _read_source_profile(agents_dir, agent_name)
        persona_path = os.path.join(agent_dir, "persona.md")
        persona = _read_text(persona_path).rstrip() if os.path.isfile(persona_path) else ""

        blocks = _build_pattern_blocks(agent_name, patterns_dir, arch, obs, sec)

        # Compose one self-contained instruction: shared rules, persona, role
        # profile, then the configured pattern blocks.
        sections = [s for s in (global_rules, persona, profile) if s]
        composed = "\n\n---\n\n".join(sections).rstrip()
        if blocks:
            composed = composed + "\n\n" + MARKER + "\n\n" + "\n\n".join(blocks)
        composed = composed.rstrip() + "\n"

        out_path = os.path.join(build_root, agent_name, f"{agent_name}.md")
        _write_text(out_path, composed)
        logger.info(f"Compiled {agent_name} -> build/agents/{agent_name}/{agent_name}.md")

    logger.info("Compilation completed successfully.")


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_workspace_root = os.path.abspath(os.path.join(script_dir, ".."))
    compile_harnesses(default_workspace_root)
