"""Shared runtime support for thin native host adapters.

Consumer repositories read the catalog below ``.agents/solomon``. A Git-proven
harness source checkout reads its tracked source catalog in place. Everything
rendered here contains only native metadata, configuration, and pointers back
to the selected catalog. This keeps host vocabulary out of workflow and
specialist definitions and makes three-host parity deterministic.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import stat
import subprocess
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, BinaryIO, Mapping, Optional

from solomon_harness.adapter_ownership import (
    AdapterOwnershipError,
    TEXT_END as _TEXT_END,
    TEXT_START as _TEXT_START,
    TOML_END as _TOML_END,
    TOML_START as _TOML_START,
    managed_adapter_digest,
    strategy_for_adapter,
)
from solomon_harness.install_transaction import (
    ensure_install_parent,
    record_install_mutation,
)
from solomon_harness.layout import HarnessPaths, confined_read_path


HOSTS = ("agy", "claude", "codex")
CAPABILITIES = {
    "headless",
    "instructions",
    "mcp",
    "pre_tool_guard",
    "session_start",
    "specialists",
    "workflows",
}

_GENERATED_MARKER = "Generated by solomon-harness; edit the source under .agents/solomon."
_LEGACY_GENERATED_MARKER = "This file is generated by scripts/generate-integrations.py."
_MCP_COMMAND = "uv"
_ADAPTER_FILE_MODE = 0o644
_CAPABILITY_STATES = {
    "active",
    "configured",
    "disabled",
    "pending_trust",
    "unavailable",
}


@dataclass(frozen=True)
class AdapterCompileResult:
    """Observable effects of one adapter compilation."""

    changed: bool
    conflicts: tuple[str, ...] = ()
    managed_paths: tuple[str, ...] = ()


@dataclass(frozen=True)
class _Specialist:
    name: str
    description: str
    directory: Path


@dataclass(frozen=True)
class _Workflow:
    name: str
    description: str
    source: Path


@dataclass(frozen=True)
class _RuntimeLayout:
    """Runtime command paths for either an installed consumer or source tree."""

    source_checkout: bool
    project_argument: str
    environment_path: str
    project_subpath: str
    marker_paths: tuple[str, ...]

    def mcp_args(self) -> list[str]:
        return [
            "run",
            "--frozen",
            "--project",
            self.project_argument,
            "python",
            "-I",
            "-m",
            "solomon_harness.mcp_server",
        ]

    def mcp_env(self) -> dict[str, str]:
        return {"UV_PROJECT_ENVIRONMENT": self.environment_path}


@dataclass(frozen=True)
class _OwnedAdapter:
    sha256: str
    mode: int
    managed_sha256: str | None = None


def _runtime_layout(source_checkout: bool) -> _RuntimeLayout:
    if source_checkout:
        return _RuntimeLayout(
            source_checkout=True,
            project_argument=".",
            environment_path=".agents/solomon/state/venv",
            project_subpath="",
            marker_paths=(
                "pyproject.toml",
                "solomon_harness/__init__.py",
                "solomon_harness/mcp_server.py",
                "scripts/generate-integrations.py",
            ),
        )
    return _RuntimeLayout(
        source_checkout=False,
        project_argument=".agents/solomon",
        environment_path="state/venv",
        project_subpath="/.agents/solomon",
        marker_paths=(
            ".agents/solomon/pyproject.toml",
            ".agents/solomon/solomon_harness/mcp_server.py",
        ),
    )


def _runtime_project_is_valid(root: Path, runtime: _RuntimeLayout) -> bool:
    """Confirm that a generated MCP command points at an in-repository runtime."""

    project = root if runtime.source_checkout else root / ".agents" / "solomon"
    try:
        project.resolve().relative_to(root.resolve())
    except (OSError, ValueError):
        return False
    required = (
        project / "pyproject.toml",
        project / "solomon_harness" / "mcp_server.py",
    )
    return all(path.is_file() and not path.is_symlink() for path in required)


def _write_adapter_payload(stream: BinaryIO, payload: bytes) -> None:
    """Write and flush one temporary adapter payload before publication."""

    stream.write(payload)
    stream.flush()
    os.fsync(stream.fileno())


def _atomic_adapter_write(root: Path, path: Path, payload: bytes, mode: int) -> None:
    """Publish one deterministic adapter without exposing partial bytes."""

    ensure_install_parent(
        root,
        path,
        private_root=HarnessPaths(root).state,
    )
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        dir=path.parent,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            _write_adapter_payload(stream, payload)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
        # Register immediately after the atomic visibility point. If the
        # directory durability flush fails, an install transaction can now
        # compare-and-swap the published bytes back to its snapshot.
        record_install_mutation(path)
        if os.name != "nt":
            directory = os.open(path.parent, os.O_RDONLY)
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
    finally:
        temporary_existed = temporary.exists()
        temporary.unlink(missing_ok=True)
        if temporary_existed:
            record_install_mutation(path.parent)


class _Recorder:
    def __init__(
        self, root: Path, previous_ownership: Mapping[str, _OwnedAdapter]
    ) -> None:
        self.root = root
        self.previous_ownership = previous_ownership
        self.changed = False
        self.conflicts: set[str] = set()
        self.managed: set[str] = set()
        self._source_checkout: Optional[bool] = None

    def relative(self, path: Path) -> str:
        return path.relative_to(self.root).as_posix()

    def conflict(self, path: Path) -> None:
        self.conflicts.add(self.relative(path))

    def mark_managed(self, path: Path) -> None:
        ensure_install_parent(
            self.root,
            path,
            private_root=HarnessPaths(self.root).state,
        )
        previous = self.previous_ownership.get(self.relative(path))
        if previous is not None and not self.mode_unchanged(path):
            self.conflict(path)
            return
        self.managed.add(self.relative(path))

    def mode_unchanged(self, path: Path) -> bool:
        previous = self.previous_ownership.get(self.relative(path))
        try:
            mode = stat.S_IMODE(path.stat().st_mode)
        except OSError:
            return False
        return previous is not None and previous.mode == mode

    def owned_unchanged(self, path: Path) -> bool:
        previous = self.previous_ownership.get(self.relative(path))
        if not previous or not path.is_file() or path.is_symlink():
            return False
        if previous.managed_sha256 is not None:
            try:
                digest = managed_adapter_digest(path, self.relative(path))
            except (OSError, RuntimeError, ValueError):
                return False
        else:
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
        return bool(
            (previous.managed_sha256 or previous.sha256) == digest
            and self.mode_unchanged(path)
        )

    def clean_tracked_source_adapter(self, path: Path) -> bool:
        """Prove ownership of a manifest-free adapter in the source checkout."""

        if not self._is_source_checkout() or not path.is_file() or path.is_symlink():
            return False
        relative = self.relative(path)
        tracked = self._git("ls-files", "--error-unmatch", "--", relative)
        clean = self._git("diff", "--quiet", "HEAD", "--", relative)
        return bool(
            tracked
            and tracked.returncode == 0
            and clean
            and clean.returncode == 0
        )

    def is_managed(self, path: Path) -> bool:
        return bool(
            self.relative(path) in self.previous_ownership
            or self.clean_tracked_source_adapter(path)
        )

    def managed_unchanged(self, path: Path) -> bool:
        if self.relative(path) in self.previous_ownership:
            return self.owned_unchanged(path)
        return self.clean_tracked_source_adapter(path)

    def unsafe(self, path: Path) -> bool:
        """Reject adapter targets that traverse symlinks or leave the project."""

        try:
            path.parent.resolve().relative_to(self.root.resolve())
        except ValueError:
            return True
        cursor = path
        while cursor != self.root:
            if cursor.is_symlink():
                return True
            cursor = cursor.parent
        return False

    def _git(self, *arguments: str, capture: bool = False) -> subprocess.CompletedProcess[str] | None:
        environment = dict(os.environ)
        for key in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE"):
            environment.pop(key, None)
        try:
            return subprocess.run(  # noqa: S603 - private callers supply fixed Git argv
                ["git", "-C", str(self.root), *arguments],  # noqa: S607 - operator PATH
                check=False,
                env=environment,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE if capture else subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                text=True,
            )
        except OSError:
            return None

    def _is_source_checkout(self) -> bool:
        """Prove this is the harness source tree, rather than a consumer repo."""

        if self._source_checkout is not None:
            return self._source_checkout
        top_level = self._git("rev-parse", "--show-toplevel", capture=True)
        source_paths = (
            "pyproject.toml",
            "agents/AGENTS.md",
            "solomon_harness/__init__.py",
            "solomon_harness/mcp_server.py",
            "scripts/generate-integrations.py",
        )
        tracked = tuple(
            self._git("ls-files", "--error-unmatch", "--", relative)
            for relative in source_paths
        )
        try:
            git_root = Path(top_level.stdout.strip()).resolve() if top_level else None
            metadata = tomllib.loads(
                (self.root / "pyproject.toml").read_text(encoding="utf-8")
            )
            project = metadata.get("project", {})
            project_name = project.get("name") if isinstance(project, Mapping) else None
        except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError):
            git_root = None
            project_name = None
        self._source_checkout = bool(
            top_level
            and top_level.returncode == 0
            and git_root == self.root.resolve()
            and project_name == "solomon-harness"
            and all(
                process is not None and process.returncode == 0 for process in tracked
            )
            and all(
                (self.root / relative).is_file()
                and not (self.root / relative).is_symlink()
                for relative in source_paths
            )
        )
        return self._source_checkout

    def clean_tracked_generated_source(self, path: Path, current: bytes) -> bool:
        """Allow a manifest-free upgrade only with independent Git ownership proof."""

        if not self._is_source_checkout():
            return False
        try:
            text = current.decode("utf-8")
        except UnicodeDecodeError:
            return False
        if not any(marker in text for marker in (_GENERATED_MARKER, _LEGACY_GENERATED_MARKER)):
            return False
        return self.clean_tracked_source_adapter(path)

    def write_generated(self, path: Path, content: str) -> None:
        """Write an owned whole-file adapter without clobbering user content."""

        if self.unsafe(path):
            self.conflict(path)
            return
        ensure_install_parent(
            self.root,
            path,
            private_root=HarnessPaths(self.root).state,
        )
        payload = content.encode("utf-8")
        rel = self.relative(path)
        if path.exists():
            current = path.read_bytes()
            if current == payload:
                self.mark_managed(path)
                return
            previous_matches = self.owned_unchanged(path)
            if not previous_matches and not self.clean_tracked_generated_source(
                path, current
            ):
                self.conflict(path)
                return
        _atomic_adapter_write(self.root, path, payload, _ADAPTER_FILE_MODE)
        self.changed = True
        self.managed.add(rel)

    def write_merged(self, path: Path, content: str) -> None:
        """Write a semantic merge that already retained unrelated content."""

        if self.unsafe(path):
            self.conflict(path)
            return
        ensure_install_parent(
            self.root,
            path,
            private_root=HarnessPaths(self.root).state,
        )
        payload = content.encode("utf-8")
        if (
            path.exists()
            and self.relative(path) in self.previous_ownership
            and not self.mode_unchanged(path)
        ):
            self.conflict(path)
            return
        if path.exists() and path.read_bytes() == payload:
            self.mark_managed(path)
            return
        mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else _ADAPTER_FILE_MODE
        _atomic_adapter_write(self.root, path, payload, mode)
        self.changed = True
        self.managed.add(self.relative(path))

    def result(self) -> AdapterCompileResult:
        return AdapterCompileResult(
            changed=self.changed,
            conflicts=tuple(sorted(self.conflicts)),
            managed_paths=tuple(sorted(self.managed)),
        )


def _load_previous_ownership(root: Path) -> dict[str, _OwnedAdapter]:
    manifest = root / ".agents" / "solomon" / "manifest.json"
    if not manifest.exists():
        return {}
    if manifest.is_symlink() or not manifest.is_file():
        raise AdapterOwnershipError(
            f"Install manifest is not a regular file: {manifest}"
        )
    try:
        document = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise AdapterOwnershipError(
            f"Cannot read install manifest: {manifest}"
        ) from exc
    if not isinstance(document, Mapping):
        raise AdapterOwnershipError("Install manifest must be a JSON object")
    if document.get("schema_version") != 1:
        raise AdapterOwnershipError("Unsupported install manifest schema")

    result: dict[str, _OwnedAdapter] = {}
    seen: set[str] = set()
    entries = document.get("entries")
    if not isinstance(entries, list):
        raise AdapterOwnershipError("Install manifest entries must be a list")
    for entry in entries:
        if not isinstance(entry, Mapping):
            raise AdapterOwnershipError("Install manifest contains an invalid entry")
        path = entry.get("path")
        owner = entry.get("owner")
        strategy = entry.get("strategy")
        digest = entry.get("sha256")
        mode = entry.get("mode")
        managed_digest = entry.get("managed_sha256")
        if not isinstance(path, str) or not _safe_manifest_path(path):
            raise AdapterOwnershipError(
                f"Install manifest contains an unsafe path: {path!r}"
            )
        if path in seen:
            raise AdapterOwnershipError(
                f"Install manifest contains a duplicate path: {path}"
            )
        seen.add(path)
        if owner not in {"adapter", "core", "project"}:
            raise AdapterOwnershipError(
                f"Install manifest contains an invalid owner for {path}"
            )
        if strategy not in {
            "replace",
            "create-only",
            "json-merge",
            "toml-merge",
            "marker-merge",
        }:
            raise AdapterOwnershipError(
                f"Install manifest contains an invalid strategy for {path}"
            )
        if not isinstance(digest, str) or re.fullmatch(
            r"[0-9a-f]{64}", digest
        ) is None:
            raise AdapterOwnershipError(
                f"Install manifest contains an invalid digest for {path}"
            )
        if not isinstance(mode, str) or re.fullmatch(r"0[0-7]{3}", mode) is None:
            raise AdapterOwnershipError(
                f"Install manifest contains an invalid mode for {path}"
            )
        if "created" in entry and not isinstance(entry["created"], bool):
            raise AdapterOwnershipError(
                f"Install manifest contains an invalid creation marker for {path}"
            )
        base_digest = entry.get("base_sha256")
        if base_digest is not None and (
            not isinstance(base_digest, str)
            or re.fullmatch(r"[0-9a-f]{64}", base_digest) is None
        ):
            raise AdapterOwnershipError(
                f"Install manifest contains an invalid base digest for {path}"
            )
        if managed_digest is not None and (
            owner != "adapter"
            or strategy not in {"json-merge", "toml-merge", "marker-merge"}
            or not isinstance(managed_digest, str)
            or re.fullmatch(r"[0-9a-f]{64}", managed_digest) is None
        ):
            raise AdapterOwnershipError(
                f"Install manifest contains an invalid managed digest for {path}"
            )
        if owner == "adapter":
            if not _adapter_manifest_path_allowed(path):
                raise AdapterOwnershipError(
                    f"Install manifest adapter path is outside its namespace: {path}"
                )
            if strategy != strategy_for_adapter(path):
                raise AdapterOwnershipError(
                    f"Install manifest adapter strategy does not match {path}"
                )
            result[path] = _OwnedAdapter(digest, int(mode, 8), managed_digest)
        elif owner == "core":
            if not path.startswith(".agents/solomon/") or path in {
                ".agents/solomon/config/project.json",
                ".agents/solomon/manifest.json",
            }:
                raise AdapterOwnershipError(
                    f"Install manifest core path is outside its namespace: {path}"
                )
            if strategy not in {"replace", "create-only"}:
                raise AdapterOwnershipError(
                    f"Install manifest core strategy does not match {path}"
                )
        else:
            if not _project_manifest_path_allowed(path):
                raise AdapterOwnershipError(
                    f"Install manifest project path is outside its namespace: {path}"
                )
            if strategy != "create-only":
                raise AdapterOwnershipError(
                    f"Install manifest project strategy does not match {path}"
                )
    return result


def _safe_manifest_path(relative: str) -> bool:
    path = Path(relative)
    return bool(
        relative
        and not path.is_absolute()
        and path.as_posix() == relative
        and "." not in path.parts
        and ".." not in path.parts
    )


def _adapter_manifest_path_allowed(relative: str) -> bool:
    fixed = {
        ".agents/hooks.json",
        ".agents/mcp_config.json",
        ".agents/plugins/solomon/mcp_config.json",
        ".agents/plugins/solomon/plugin.json",
        ".claude/CLAUDE.md",
        ".claude/settings.json",
        ".codex/config.toml",
        ".codex/hooks.json",
        ".mcp.json",
        "AGENTS.md",
    }
    if relative in fixed:
        return True
    parts = Path(relative).parts
    return bool(
        (
            len(parts) == 4
            and parts[:2] == (".agents", "agents")
            and parts[2]
            and parts[3] == "agent.md"
        )
        or (
            len(parts) == 4
            and parts[:2] == (".agents", "skills")
            and parts[2].startswith("solomon-")
            and parts[3] == "SKILL.md"
        )
        or (
            len(parts) == 3
            and parts[:2] == (".claude", "agents")
            and parts[2].endswith(".md")
        )
        or (
            len(parts) == 4
            and parts[:2] == (".claude", "skills")
            and parts[2].startswith("solomon-")
            and parts[3] == "SKILL.md"
        )
        or (
            len(parts) == 3
            and parts[:2] == (".codex", "agents")
            and parts[2].endswith(".toml")
        )
    )


def _project_manifest_path_allowed(relative: str) -> bool:
    if relative == ".agents/solomon/config/project.json":
        return True
    if relative in {
        ".github/PULL_REQUEST_TEMPLATE.md",
        "docs/adrs/0000-adr-template.md",
        "docs/adrs/README.md",
        "docs/specs/0000-spec-template.md",
        "docs/specs/README.md",
    }:
        return True
    parts = Path(relative).parts
    return len(parts) == 3 and parts[:2] == (".github", "ISSUE_TEMPLATE")


@dataclass(frozen=True)
class HostCompileContext:
    """Neutral inputs and write boundary supplied to one host compiler."""

    root: Path
    paths: HarnessPaths
    specialists: tuple[_Specialist, ...]
    workflows: tuple[_Workflow, ...]
    rules: Path
    runtime: _RuntimeLayout
    recorder: _Recorder
    mcp_command: str


@dataclass(frozen=True)
class HostInspectionContext:
    """Neutral expectations supplied to one host capability inspector."""

    root: Path
    paths: HarnessPaths
    runtime: _RuntimeLayout
    expected_specialists: tuple[str, ...]
    expected_workflows: tuple[str, ...]
    agents_reference: str
    rules_reference: str
    workflow_references: Mapping[str, str]
    shared_workflows: tuple[str, ...]
    mcp_command: str


def _single_line(value: str, fallback: str) -> str:
    compact = " ".join(value.replace("\u2014", "-").split())
    return compact or fallback


def _frontmatter_value(text: str, key: str) -> str:
    if not text.startswith("---"):
        return ""
    sections = text.split("---", 2)
    if len(sections) < 3:
        return ""
    prefix = key.lower() + ":"
    for line in sections[1].splitlines():
        stripped = line.strip()
        if stripped.lower().startswith(prefix):
            return stripped.split(":", 1)[1].strip().strip('"\'')
    return ""


def _markdown_description(path: Path, fallback: str) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return fallback
    frontmatter = _frontmatter_value(text, "description")
    if frontmatter:
        return _single_line(frontmatter, fallback)
    paragraph: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped == "---" or stripped.startswith("#"):
            if paragraph:
                break
            continue
        if stripped.startswith(("- ", "* ", "```")):
            if paragraph:
                break
            continue
        paragraph.append(stripped)
    return _single_line(" ".join(paragraph), fallback)


def _specialist_description(path: Path, fallback: str) -> str:
    """Combine a specialist's role summary with its delegation trigger."""

    description = _markdown_description(path, fallback)
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return description
    in_delegation_cue = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            in_delegation_cue = stripped.lower() == "## delegation cue"
            continue
        if not in_delegation_cue or not stripped or stripped.startswith("#"):
            continue
        cue = _single_line(stripped, "")
        if cue and cue not in description:
            return _single_line(f"{description} {cue}", fallback)
        break
    return description


def _catalog(root: Path) -> tuple[list[_Specialist], list[_Workflow], Path]:
    paths = HarnessPaths(root)
    agents_root = confined_read_path(root, paths.resolve_agents())
    workflows_root = confined_read_path(root, paths.resolve_workflows())
    rules = confined_read_path(root, paths.resolve_rules())

    specialists: list[_Specialist] = []
    if agents_root.is_dir():
        for candidate in sorted(agents_root.iterdir(), key=lambda item: item.name):
            directory = confined_read_path(root, candidate)
            if not directory.is_dir() or directory.name.startswith("."):
                continue
            role = confined_read_path(
                root,
                directory / "agents" / f"{directory.name}.md",
            )
            if not role.is_file():
                continue
            fallback = f"Use the {directory.name} Solomon specialist."
            specialists.append(
                _Specialist(
                    name=directory.name,
                    description=_specialist_description(role, fallback),
                    directory=directory,
                )
            )

    workflows: list[_Workflow] = []
    if workflows_root.is_dir():
        candidates = sorted(workflows_root.glob("*.md"), key=lambda item: item.name)
        for candidate in candidates:
            source = confined_read_path(root, candidate)
            stem = source.stem
            if stem.startswith("solomon-"):
                name = stem.removeprefix("solomon-")
            elif stem not in {"README", "AGENTS"}:
                name = stem
            else:
                continue
            fallback = f"Run the Solomon {name} workflow."
            workflows.append(
                _Workflow(
                    name=name,
                    description=_markdown_description(source, fallback),
                    source=source,
                )
            )

    if not specialists:
        raise FileNotFoundError(f"no specialist catalog found below {agents_root}")
    if not workflows:
        raise FileNotFoundError(f"no workflow catalog found below {workflows_root}")
    return specialists, workflows, rules


def _reference(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError as exc:
        raise ValueError(f"adapter source escapes project root: {path}") from exc


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _specialist_markdown(
    specialist: _Specialist,
    *,
    root: Path,
    rules: Path,
) -> str:
    directory = _reference(root, specialist.directory)
    rule_path = _reference(root, rules)
    return (
        "---\n"
        f"name: {specialist.name}\n"
        f"description: {_yaml_string(specialist.description)}\n"
        "---\n\n"
        f"<!-- {_GENERATED_MARKER} -->\n"
        f"Read `{rule_path}`, `{directory}/persona.md`, "
        f"`{directory}/agents/{specialist.name}.md`, and the relevant files in "
        f"`{directory}/skills/` before acting. Follow those canonical instructions.\n"
    )


def _workflow_skill(
    workflow: _Workflow,
    root: Path,
    *,
    allowed_tools: str = "",
) -> str:
    source = _reference(root, workflow.source)
    skill_name = f"solomon-{workflow.name}"
    host_metadata = f"allowed-tools: {allowed_tools}\n" if allowed_tools else ""
    return (
        "---\n"
        f"name: {skill_name}\n"
        f"description: {_yaml_string(workflow.description)}\n"
        f"{host_metadata}"
        "---\n\n"
        f"<!-- {_GENERATED_MARKER} -->\n"
        f"Read and follow `{source}`. Treat all arguments supplied with this skill as "
        "the workflow arguments. The referenced file is the canonical workflow.\n"
    )


def _merge_marker_text(existing: str, body: str) -> Optional[str]:
    block = f"{_TEXT_START}\n{body.rstrip()}\n{_TEXT_END}"
    start_count = existing.count(_TEXT_START)
    end_count = existing.count(_TEXT_END)
    if start_count != end_count or start_count > 1:
        return None
    if start_count:
        before, remainder = existing.split(_TEXT_START, 1)
        _, after = remainder.split(_TEXT_END, 1)
        prefix = before.rstrip()
        merged = (prefix + "\n\n" if prefix else "") + block + after
    elif existing.strip():
        merged = existing.rstrip() + "\n\n" + block + "\n"
    else:
        merged = block + "\n"
    return merged


def _text_managed_block(existing: str) -> Optional[str]:
    start_count = existing.count(_TEXT_START)
    end_count = existing.count(_TEXT_END)
    if start_count != end_count or start_count > 1:
        raise ValueError("invalid Solomon instruction markers")
    if not start_count:
        return None
    _, remainder = existing.split(_TEXT_START, 1)
    managed, _ = remainder.split(_TEXT_END, 1)
    return f"{_TEXT_START}{managed}{_TEXT_END}"


def _write_marker_file(recorder: _Recorder, path: Path, body: str) -> None:
    if recorder.unsafe(path):
        recorder.conflict(path)
        return
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = ""
    except (OSError, UnicodeDecodeError):
        recorder.conflict(path)
        return
    desired_block = f"{_TEXT_START}\n{body.rstrip()}\n{_TEXT_END}"
    try:
        current_block = _text_managed_block(existing)
    except ValueError:
        recorder.conflict(path)
        return
    previously_managed = recorder.is_managed(path)
    if current_block is not None:
        if current_block == desired_block:
            recorder.mark_managed(path)
            return
        if not previously_managed:
            recorder.conflict(path)
            return
        if not recorder.managed_unchanged(path):
            recorder.conflict(path)
            return
    elif previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    merged = _merge_marker_text(existing, body)
    if merged is None:
        recorder.conflict(path)
        return
    recorder.write_merged(path, merged)


def _read_json_object(path: Path, recorder: _Recorder) -> Optional[dict[str, Any]]:
    if recorder.unsafe(path):
        recorder.conflict(path)
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        recorder.conflict(path)
        return None
    if not isinstance(value, dict):
        recorder.conflict(path)
        return None
    return value


def _write_json(recorder: _Recorder, path: Path, value: Mapping[str, Any]) -> None:
    recorder.write_merged(
        path,
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )


def _append_unique(values: Any, item: Mapping[str, Any]) -> list[Any]:
    result = list(values) if isinstance(values, list) else []
    if item not in result:
        result.append(dict(item))
    return result


def _runtime_hook_command(
    host: str, event: str, runtime: _RuntimeLayout
) -> str:
    """Build a POSIX hook command that is independent of the session cwd.

    Claude and AGY currently expose only their shell ``command`` field here,
    so those two adapters require a POSIX-compatible shell on Windows. Codex's
    native schema supports a Windows override and receives one below.
    """

    marker = " && ".join(
        f'[ -f "$SOLOMON_ROOT/{relative}" ]' for relative in runtime.marker_paths
    )
    project = f'$SOLOMON_ROOT{runtime.project_subpath}'
    return (
        '{ SOLOMON_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" && '
        f"{marker}; }} || "
        '{ SOLOMON_ROOT="$PWD"; while [ "$SOLOMON_ROOT" != "/" ]; do '
        f"{marker} && break; "
        'SOLOMON_ROOT="$(dirname "$SOLOMON_ROOT")"; done; '
        f"{marker}; }} && "
        'UV_PROJECT_ENVIRONMENT="$SOLOMON_ROOT/.agents/solomon/state/venv" '
        f'uv run --frozen --project "{project}" '
        f"python -I -m solomon_harness.cli host-hook {event} --host {host}"
    )


def _windows_runtime_hook_command(
    host: str, event: str, runtime: _RuntimeLayout
) -> str:
    """Build Codex's Windows override using cmd's native Git-root lookup.

    Unlike the POSIX launcher, this requires a Git worktree; the native Codex
    override is explicit so the POSIX ancestor-search syntax is never sent to
    ``cmd.exe``.
    """

    project = f"%R{runtime.project_subpath.replace('/', chr(92))}"
    return (
        'for /f "delims=" %R in (\'git rev-parse --show-toplevel\') do '
        'set "UV_PROJECT_ENVIRONMENT=%R\\.agents\\solomon\\state\\venv" && '
        f'uv run --frozen --project "{project}" '
        f"python -I -m solomon_harness.cli host-hook {event} --host {host}"
    )


def _hook_handler(
    host: str, event: str, runtime: _RuntimeLayout
) -> dict[str, Any]:
    handler: dict[str, Any] = {
        "command": _runtime_hook_command(host, event, runtime),
        "timeout": 30,
        "type": "command",
    }
    if host == "codex":
        handler["commandWindows"] = _windows_runtime_hook_command(
            host, event, runtime
        )
    return handler


def _contains_host_hook(value: Any, host: str) -> bool:
    text = json.dumps(value, sort_keys=True)
    return "solomon_harness.cli host-hook" in text and f"--host {host}" in text


def _host_hook_nodes(hooks: Mapping[str, Any], host: str) -> list[tuple[str, Any]]:
    result: list[tuple[str, Any]] = []
    for event, values in hooks.items():
        if not isinstance(values, list):
            continue
        result.extend(
            (event, item) for item in values if _contains_host_hook(item, host)
        )
    return result


def _host_hook_specs_are_exact(
    hooks: Mapping[str, Any], host: str, desired: Mapping[str, Mapping[str, Any]]
) -> bool:
    actual = _host_hook_nodes(hooks, host)
    if len(actual) != len(desired):
        return False
    return all(
        sum(1 for actual_event, node in actual if actual_event == event and node == specification)
        == 1
        for event, specification in desired.items()
    )


def _remove_host_hook_nodes(hooks: dict[str, Any], host: str) -> None:
    for event in list(hooks):
        values = hooks[event]
        if not isinstance(values, list):
            continue
        retained = [item for item in values if not _contains_host_hook(item, host)]
        if retained:
            hooks[event] = retained
        else:
            hooks.pop(event)


def _merge_list_hooks(
    recorder: _Recorder,
    path: Path,
    host: str,
    desired: Mapping[str, Mapping[str, Any]],
) -> None:
    document = _read_json_object(path, recorder)
    if document is None:
        return
    hooks = document.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        recorder.conflict(path)
        return
    if any(event in hooks and not isinstance(hooks[event], list) for event in desired):
        recorder.conflict(path)
        return

    previously_managed = recorder.is_managed(path)
    host_nodes = _host_hook_nodes(hooks, host)
    exact = _host_hook_specs_are_exact(hooks, host, desired)
    if exact:
        recorder.mark_managed(path)
        return
    if not previously_managed and host_nodes:
        recorder.conflict(path)
        return
    if previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    if previously_managed:
        _remove_host_hook_nodes(hooks, host)
    for event, specification in desired.items():
        hooks[event] = _append_unique(hooks.get(event), specification)
    _write_json(recorder, path, document)


def _merge_mcp_json(
    recorder: _Recorder,
    path: Path,
    runtime: _RuntimeLayout,
    mcp_command: str = _MCP_COMMAND,
) -> None:
    document = _read_json_object(path, recorder)
    if document is None:
        return
    servers = document.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        recorder.conflict(path)
        return
    desired = {
        "args": runtime.mcp_args(),
        "command": mcp_command,
        "env": runtime.mcp_env(),
    }
    previously_managed = recorder.is_managed(path)
    if "solomon-memory" in servers:
        existing = servers["solomon-memory"]
        if existing == desired:
            recorder.mark_managed(path)
            return
        if not previously_managed or not recorder.managed_unchanged(path):
            recorder.conflict(path)
            return
    elif previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    servers["solomon-memory"] = desired
    _write_json(recorder, path, document)


def _merge_toml_marker(existing: str, body: str) -> Optional[str]:
    block = f"{_TOML_START}\n{body.rstrip()}\n{_TOML_END}"
    start_count = existing.count(_TOML_START)
    end_count = existing.count(_TOML_END)
    if start_count != end_count or start_count > 1:
        return None
    if start_count:
        before, remainder = existing.split(_TOML_START, 1)
        _, after = remainder.split(_TOML_END, 1)
        prefix = before.rstrip()
        return (prefix + "\n\n" if prefix else "") + block + after
    if re.search(r"(?m)^\s*\[\s*mcp_servers\.solomon-memory\s*]\s*$", existing):
        return None
    if existing.strip():
        return existing.rstrip() + "\n\n" + block + "\n"
    return block + "\n"


def _toml_managed_block(existing: str) -> Optional[str]:
    start_count = existing.count(_TOML_START)
    end_count = existing.count(_TOML_END)
    if start_count != end_count or start_count > 1:
        raise ValueError("invalid Solomon TOML markers")
    if not start_count:
        return None
    _, remainder = existing.split(_TOML_START, 1)
    managed, _ = remainder.split(_TOML_END, 1)
    return f"{_TOML_START}{managed}{_TOML_END}"


def _read_text(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def _valid_generated_text(path: Path, *required: str) -> bool:
    text = _read_text(path)
    return bool(
        text is not None
        and _GENERATED_MARKER in text
        and all(fragment in text for fragment in required)
    )


def _specialist_names(
    directory: Path, host: str, agents_reference: str
) -> tuple[str, ...]:
    if not directory.is_dir():
        return ()
    result: list[str] = []
    if host == "agy":
        candidates = sorted(directory.iterdir())
        for candidate in candidates:
            path = candidate / "agent.md"
            if candidate.is_dir() and _valid_generated_text(
                path, f"{agents_reference}/{candidate.name}"
            ):
                result.append(candidate.name)
        return tuple(result)
    if host == "claude":
        candidates = sorted(directory.glob("*.md"))
        for path in candidates:
            if _valid_generated_text(
                path, f"{agents_reference}/{path.stem}"
            ):
                result.append(path.stem)
        return tuple(result)
    if host == "codex":
        candidates = sorted(directory.glob("*.toml"))
        for path in candidates:
            text = _read_text(path)
            if text is None or _GENERATED_MARKER not in text:
                continue
            try:
                document = tomllib.loads(text)
            except tomllib.TOMLDecodeError:
                continue
            if (
                document.get("name") == path.stem
                and f"{agents_reference}/{path.stem}"
                in str(document.get("developer_instructions", ""))
            ):
                result.append(path.stem)
        return tuple(result)
    raise ValueError(f"unknown specialist host: {host}")


def _skill_names(
    directory: Path, workflow_references: Mapping[str, str]
) -> tuple[str, ...]:
    if not directory.is_dir():
        return ()
    return tuple(
        sorted(
            child.name.removeprefix("solomon-")
            for child in directory.iterdir()
            if child.is_dir()
            and child.name.startswith("solomon-")
            and child.name.removeprefix("solomon-") in workflow_references
            and _valid_generated_text(
                child / "SKILL.md",
                workflow_references[child.name.removeprefix("solomon-")],
            )
        )
    )


def _read_json(path: Path) -> Optional[dict[str, Any]]:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    return document if isinstance(document, dict) else None


def _valid_hooks(
    path: Path,
    host: str,
    desired: Mapping[str, Mapping[str, Any]],
) -> bool:
    document = _read_json(path)
    if document is None:
        return False
    if host == "agy":
        return all(document.get(key) == value for key, value in desired.items())
    hooks = document.get("hooks")
    return bool(
        isinstance(hooks, dict)
        and _host_hook_specs_are_exact(
            hooks, host, desired
        )
    )


def _valid_json_mcp(
    path: Path,
    root: Path,
    runtime: _RuntimeLayout,
    mcp_command: str = _MCP_COMMAND,
) -> bool:
    document = _read_json(path)
    if document is None:
        return False
    servers = document.get("mcpServers")
    desired = {
        "args": runtime.mcp_args(),
        "command": mcp_command,
        "env": runtime.mcp_env(),
    }
    return bool(
        _runtime_project_is_valid(root, runtime)
        and isinstance(servers, dict)
        and servers.get("solomon-memory") == desired
    )


def _read_toml(path: Path) -> Optional[dict[str, Any]]:
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError):
        return None
    return document if isinstance(document, dict) else None


def _instruction_is_valid(
    path: Path, host: str, rules_reference: str
) -> bool:
    text = _read_text(path)
    if text is None or _TEXT_START not in text or _TEXT_END not in text:
        return False
    if host == "claude":
        return f"@../{rules_reference}" in text
    return rules_reference in text


def _overall_status(states: Mapping[str, str]) -> str:
    configured = {state for state in states.values() if state != "unavailable"}
    if "disabled" in configured:
        return "disabled"
    if "pending_trust" in configured:
        return "pending_trust"
    if "configured" in configured:
        return "configured"
    return "active" if configured else "unavailable"
