"""Compile a neutral harness catalog into thin native host adapters.

Consumer repositories read the catalog below ``.agents/solomon``. A Git-proven
harness source checkout reads its tracked source catalog in place. Everything
rendered here contains only native metadata, configuration, and pointers back
to the selected catalog. This keeps host vocabulary out of workflow and
specialist definitions and makes three-host parity deterministic.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import stat
import subprocess
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Optional


HOSTS = ("agy", "claude", "codex")
CAPABILITIES = {
    "headless",
    "instructions",
    "mcp",
    "pre_tool_guard",
    "session_start",
    "specialists",
    "workflows",
}

_GENERATED_MARKER = "Generated by solomon-harness; edit the source under .agents/solomon."
_LEGACY_GENERATED_MARKER = "This file is generated by scripts/generate-integrations.py."
_TEXT_START = "<!-- solomon-harness:start -->"
_TEXT_END = "<!-- solomon-harness:end -->"
_TOML_START = "# >>> solomon-harness managed adapter >>>"
_TOML_END = "# <<< solomon-harness managed adapter <<<"
_MCP_COMMAND = "uv"
_CAPABILITY_STATES = {"active", "configured", "pending_trust", "unavailable"}


@dataclass(frozen=True)
class AdapterCompileResult:
    """Observable effects of one adapter compilation."""

    changed: bool
    conflicts: tuple[str, ...] = ()
    managed_paths: tuple[str, ...] = ()


@dataclass(frozen=True)
class _Specialist:
    name: str
    description: str
    directory: Path


@dataclass(frozen=True)
class _Workflow:
    name: str
    description: str
    source: Path


@dataclass(frozen=True)
class _RuntimeLayout:
    """Runtime command paths for either an installed consumer or source tree."""

    source_checkout: bool
    project_argument: str
    environment_path: str
    project_subpath: str
    marker_paths: tuple[str, ...]

    def mcp_args(self) -> list[str]:
        return [
            "run",
            "--frozen",
            "--project",
            self.project_argument,
            "python",
            "-m",
            "solomon_harness.mcp_server",
        ]

    def mcp_env(self) -> dict[str, str]:
        return {"UV_PROJECT_ENVIRONMENT": self.environment_path}


@dataclass(frozen=True)
class _OwnedAdapter:
    sha256: str
    mode: int
    managed_sha256: str | None = None


def _runtime_layout(source_checkout: bool) -> _RuntimeLayout:
    if source_checkout:
        return _RuntimeLayout(
            source_checkout=True,
            project_argument=".",
            environment_path=".agents/solomon/state/venv",
            project_subpath="",
            marker_paths=(
                "pyproject.toml",
                "solomon_harness/__init__.py",
                "solomon_harness/mcp_server.py",
                "scripts/generate-integrations.py",
            ),
        )
    return _RuntimeLayout(
        source_checkout=False,
        project_argument=".agents/solomon",
        environment_path="state/venv",
        project_subpath="/.agents/solomon",
        marker_paths=(
            ".agents/solomon/pyproject.toml",
            ".agents/solomon/solomon_harness/mcp_server.py",
        ),
    )


def _runtime_project_is_valid(root: Path, runtime: _RuntimeLayout) -> bool:
    """Confirm that a generated MCP command points at an in-repository runtime."""

    project = root if runtime.source_checkout else root / ".agents" / "solomon"
    try:
        project.resolve().relative_to(root.resolve())
    except (OSError, ValueError):
        return False
    required = (
        project / "pyproject.toml",
        project / "solomon_harness" / "mcp_server.py",
    )
    return all(path.is_file() and not path.is_symlink() for path in required)


class _Recorder:
    def __init__(
        self, root: Path, previous_ownership: Mapping[str, _OwnedAdapter]
    ) -> None:
        self.root = root
        self.previous_ownership = previous_ownership
        self.changed = False
        self.conflicts: set[str] = set()
        self.managed: set[str] = set()
        self._source_checkout: Optional[bool] = None

    def relative(self, path: Path) -> str:
        return path.relative_to(self.root).as_posix()

    def conflict(self, path: Path) -> None:
        self.conflicts.add(self.relative(path))

    def mark_managed(self, path: Path) -> None:
        previous = self.previous_ownership.get(self.relative(path))
        if previous is not None and not self.mode_unchanged(path):
            self.conflict(path)
            return
        self.managed.add(self.relative(path))

    def mode_unchanged(self, path: Path) -> bool:
        previous = self.previous_ownership.get(self.relative(path))
        try:
            mode = stat.S_IMODE(path.stat().st_mode)
        except OSError:
            return False
        return previous is not None and previous.mode == mode

    def owned_unchanged(self, path: Path) -> bool:
        previous = self.previous_ownership.get(self.relative(path))
        if not previous or not path.is_file() or path.is_symlink():
            return False
        if previous.managed_sha256 is not None:
            from solomon_harness.install_layout import _managed_adapter_digest

            try:
                digest = _managed_adapter_digest(path, self.relative(path))
            except (OSError, RuntimeError, ValueError):
                return False
        else:
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
        return bool(
            (previous.managed_sha256 or previous.sha256) == digest
            and self.mode_unchanged(path)
        )

    def clean_tracked_source_adapter(self, path: Path) -> bool:
        """Prove ownership of a manifest-free adapter in the source checkout."""

        if not self._is_source_checkout() or not path.is_file() or path.is_symlink():
            return False
        relative = self.relative(path)
        tracked = self._git("ls-files", "--error-unmatch", "--", relative)
        clean = self._git("diff", "--quiet", "HEAD", "--", relative)
        return bool(
            tracked
            and tracked.returncode == 0
            and clean
            and clean.returncode == 0
        )

    def is_managed(self, path: Path) -> bool:
        return bool(
            self.relative(path) in self.previous_ownership
            or self.clean_tracked_source_adapter(path)
        )

    def managed_unchanged(self, path: Path) -> bool:
        if self.relative(path) in self.previous_ownership:
            return self.owned_unchanged(path)
        return self.clean_tracked_source_adapter(path)

    def unsafe(self, path: Path) -> bool:
        """Reject adapter targets that traverse symlinks or leave the project."""

        try:
            path.parent.resolve().relative_to(self.root.resolve())
        except ValueError:
            return True
        cursor = path
        while cursor != self.root:
            if cursor.is_symlink():
                return True
            cursor = cursor.parent
        return False

    def _git(self, *arguments: str, capture: bool = False) -> subprocess.CompletedProcess[str] | None:
        environment = dict(os.environ)
        for key in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE"):
            environment.pop(key, None)
        try:
            return subprocess.run(
                ["git", "-C", str(self.root), *arguments],
                check=False,
                env=environment,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE if capture else subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                text=True,
            )
        except OSError:
            return None

    def _is_source_checkout(self) -> bool:
        """Prove this is the harness source tree, rather than a consumer repo."""

        if self._source_checkout is not None:
            return self._source_checkout
        top_level = self._git("rev-parse", "--show-toplevel", capture=True)
        source_paths = (
            "pyproject.toml",
            "agents/AGENTS.md",
            "solomon_harness/__init__.py",
            "solomon_harness/mcp_server.py",
            "scripts/generate-integrations.py",
        )
        tracked = tuple(
            self._git("ls-files", "--error-unmatch", "--", relative)
            for relative in source_paths
        )
        try:
            git_root = Path(top_level.stdout.strip()).resolve() if top_level else None
            metadata = tomllib.loads(
                (self.root / "pyproject.toml").read_text(encoding="utf-8")
            )
            project = metadata.get("project", {})
            project_name = project.get("name") if isinstance(project, Mapping) else None
        except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError):
            git_root = None
            project_name = None
        self._source_checkout = bool(
            top_level
            and top_level.returncode == 0
            and git_root == self.root.resolve()
            and project_name == "solomon-harness"
            and all(
                process is not None and process.returncode == 0 for process in tracked
            )
            and all(
                (self.root / relative).is_file()
                and not (self.root / relative).is_symlink()
                for relative in source_paths
            )
        )
        return self._source_checkout

    def clean_tracked_generated_source(self, path: Path, current: bytes) -> bool:
        """Allow a manifest-free upgrade only with independent Git ownership proof."""

        if not self._is_source_checkout():
            return False
        try:
            text = current.decode("utf-8")
        except UnicodeDecodeError:
            return False
        if not any(marker in text for marker in (_GENERATED_MARKER, _LEGACY_GENERATED_MARKER)):
            return False
        return self.clean_tracked_source_adapter(path)

    def write_generated(self, path: Path, content: str) -> None:
        """Write an owned whole-file adapter without clobbering user content."""

        if self.unsafe(path):
            self.conflict(path)
            return
        payload = content.encode("utf-8")
        rel = self.relative(path)
        if path.exists():
            current = path.read_bytes()
            if current == payload:
                self.mark_managed(path)
                return
            previous_matches = self.owned_unchanged(path)
            if not previous_matches and not self.clean_tracked_generated_source(
                path, current
            ):
                self.conflict(path)
                return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
        self.changed = True
        self.managed.add(rel)

    def write_merged(self, path: Path, content: str) -> None:
        """Write a semantic merge that already retained unrelated content."""

        if self.unsafe(path):
            self.conflict(path)
            return
        payload = content.encode("utf-8")
        if (
            path.exists()
            and self.relative(path) in self.previous_ownership
            and not self.mode_unchanged(path)
        ):
            self.conflict(path)
            return
        if path.exists() and path.read_bytes() == payload:
            self.mark_managed(path)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
        self.changed = True
        self.managed.add(self.relative(path))

    def result(self) -> AdapterCompileResult:
        return AdapterCompileResult(
            changed=self.changed,
            conflicts=tuple(sorted(self.conflicts)),
            managed_paths=tuple(sorted(self.managed)),
        )


def _load_previous_ownership(root: Path) -> dict[str, _OwnedAdapter]:
    manifest = root / ".agents" / "solomon" / "manifest.json"
    try:
        document = json.loads(manifest.read_text(encoding="utf-8"))
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return {}
    result: dict[str, _OwnedAdapter] = {}
    entries = document.get("entries", []) if isinstance(document, Mapping) else []
    if not isinstance(entries, list):
        return result
    for entry in entries:
        if not isinstance(entry, Mapping):
            continue
        path = entry.get("path")
        digest = entry.get("sha256")
        mode = entry.get("mode")
        managed_digest = entry.get("managed_sha256")
        if (
            isinstance(path, str)
            and isinstance(digest, str)
            and isinstance(mode, str)
            and re.fullmatch(r"0[0-7]{3}", mode) is not None
            and (
                managed_digest is None
                or (
                    isinstance(managed_digest, str)
                    and re.fullmatch(r"[0-9a-f]{64}", managed_digest) is not None
                )
            )
        ):
            result[path] = _OwnedAdapter(digest, int(mode, 8), managed_digest)
    return result


def _single_line(value: str, fallback: str) -> str:
    compact = " ".join(value.replace("\u2014", "-").split())
    return compact or fallback


def _frontmatter_value(text: str, key: str) -> str:
    if not text.startswith("---"):
        return ""
    sections = text.split("---", 2)
    if len(sections) < 3:
        return ""
    prefix = key.lower() + ":"
    for line in sections[1].splitlines():
        stripped = line.strip()
        if stripped.lower().startswith(prefix):
            return stripped.split(":", 1)[1].strip().strip('"\'')
    return ""


def _markdown_description(path: Path, fallback: str) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return fallback
    frontmatter = _frontmatter_value(text, "description")
    if frontmatter:
        return _single_line(frontmatter, fallback)
    paragraph: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped == "---" or stripped.startswith("#"):
            if paragraph:
                break
            continue
        if stripped.startswith(("- ", "* ", "```")):
            if paragraph:
                break
            continue
        paragraph.append(stripped)
    return _single_line(" ".join(paragraph), fallback)


def _specialist_description(path: Path, fallback: str) -> str:
    """Combine a specialist's role summary with its delegation trigger."""

    description = _markdown_description(path, fallback)
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return description
    in_delegation_cue = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            in_delegation_cue = stripped.lower() == "## delegation cue"
            continue
        if not in_delegation_cue or not stripped or stripped.startswith("#"):
            continue
        cue = _single_line(stripped, "")
        if cue and cue not in description:
            return _single_line(f"{description} {cue}", fallback)
        break
    return description


def _catalog(root: Path) -> tuple[list[_Specialist], list[_Workflow], Path]:
    from solomon_harness.layout import HarnessPaths

    paths = HarnessPaths(root)
    agents_root = paths.resolve_agents()
    workflows_root = paths.resolve_workflows()
    rules = paths.resolve_rules()

    specialists: list[_Specialist] = []
    if agents_root.is_dir():
        for directory in sorted(agents_root.iterdir(), key=lambda item: item.name):
            if not directory.is_dir() or directory.name.startswith("."):
                continue
            role = directory / "agents" / f"{directory.name}.md"
            if not role.is_file():
                continue
            fallback = f"Use the {directory.name} Solomon specialist."
            specialists.append(
                _Specialist(
                    name=directory.name,
                    description=_specialist_description(role, fallback),
                    directory=directory,
                )
            )

    workflows: list[_Workflow] = []
    if workflows_root.is_dir():
        sources = sorted(workflows_root.glob("*.md"), key=lambda item: item.name)
        for source in sources:
            stem = source.stem
            if stem.startswith("solomon-"):
                name = stem.removeprefix("solomon-")
            elif stem not in {"README", "AGENTS"}:
                name = stem
            else:
                continue
            fallback = f"Run the Solomon {name} workflow."
            workflows.append(
                _Workflow(
                    name=name,
                    description=_markdown_description(source, fallback),
                    source=source,
                )
            )

    if not specialists:
        raise FileNotFoundError(f"no specialist catalog found below {agents_root}")
    if not workflows:
        raise FileNotFoundError(f"no workflow catalog found below {workflows_root}")
    return specialists, workflows, rules


def _reference(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError as exc:
        raise ValueError(f"adapter source escapes project root: {path}") from exc


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _specialist_markdown(
    specialist: _Specialist,
    *,
    root: Path,
    rules: Path,
) -> str:
    directory = _reference(root, specialist.directory)
    rule_path = _reference(root, rules)
    return (
        "---\n"
        f"name: {specialist.name}\n"
        f"description: {_yaml_string(specialist.description)}\n"
        "---\n\n"
        f"<!-- {_GENERATED_MARKER} -->\n"
        f"Read `{rule_path}`, `{directory}/persona.md`, "
        f"`{directory}/agents/{specialist.name}.md`, and the relevant files in "
        f"`{directory}/skills/` before acting. Follow those canonical instructions.\n"
    )


def _specialist_toml(
    specialist: _Specialist,
    *,
    root: Path,
    rules: Path,
) -> str:
    directory = _reference(root, specialist.directory)
    rule_path = _reference(root, rules)
    instructions = (
        f"Read `{rule_path}`, `{directory}/persona.md`, "
        f"`{directory}/agents/{specialist.name}.md`, and the relevant files in "
        f"`{directory}/skills/` before acting. Follow those canonical instructions."
    )
    return (
        f"# {_GENERATED_MARKER}\n"
        f"name = {_yaml_string(specialist.name)}\n"
        f"description = {_yaml_string(specialist.description)}\n"
        f"developer_instructions = {_yaml_string(instructions)}\n"
    )


def _claude_allowed_tools(workflow: _Workflow, root: Path) -> str:
    """Read Claude-only permissions without leaking them into the shared skill."""

    from solomon_harness.layout import HarnessPaths

    paths = HarnessPaths(root)
    name = f"solomon-{workflow.name}.md"
    candidates = (
        paths.solomon / "host-metadata" / "claude" / "commands" / name,
        paths.legacy_workflows / name,
    )
    for candidate in candidates:
        text = _read_text(candidate)
        if text is None:
            continue
        value = _frontmatter_value(text, "allowed-tools")
        if value:
            return _single_line(value, "")
    return ""


def _workflow_skill(
    workflow: _Workflow,
    root: Path,
    *,
    allowed_tools: str = "",
) -> str:
    source = _reference(root, workflow.source)
    skill_name = f"solomon-{workflow.name}"
    host_metadata = f"allowed-tools: {allowed_tools}\n" if allowed_tools else ""
    return (
        "---\n"
        f"name: {skill_name}\n"
        f"description: {_yaml_string(workflow.description)}\n"
        f"{host_metadata}"
        "---\n\n"
        f"<!-- {_GENERATED_MARKER} -->\n"
        f"Read and follow `{source}`. Treat all arguments supplied with this skill as "
        "the workflow arguments. The referenced file is the canonical workflow.\n"
    )


def _merge_marker_text(existing: str, body: str) -> Optional[str]:
    block = f"{_TEXT_START}\n{body.rstrip()}\n{_TEXT_END}"
    start_count = existing.count(_TEXT_START)
    end_count = existing.count(_TEXT_END)
    if start_count != end_count or start_count > 1:
        return None
    if start_count:
        before, remainder = existing.split(_TEXT_START, 1)
        _, after = remainder.split(_TEXT_END, 1)
        prefix = before.rstrip()
        merged = (prefix + "\n\n" if prefix else "") + block + after
    elif existing.strip():
        merged = existing.rstrip() + "\n\n" + block + "\n"
    else:
        merged = block + "\n"
    return merged


def _text_managed_block(existing: str) -> Optional[str]:
    start_count = existing.count(_TEXT_START)
    end_count = existing.count(_TEXT_END)
    if start_count != end_count or start_count > 1:
        raise ValueError("invalid Solomon instruction markers")
    if not start_count:
        return None
    _, remainder = existing.split(_TEXT_START, 1)
    managed, _ = remainder.split(_TEXT_END, 1)
    return f"{_TEXT_START}{managed}{_TEXT_END}"


def _write_marker_file(recorder: _Recorder, path: Path, body: str) -> None:
    if recorder.unsafe(path):
        recorder.conflict(path)
        return
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = ""
    except (OSError, UnicodeDecodeError):
        recorder.conflict(path)
        return
    desired_block = f"{_TEXT_START}\n{body.rstrip()}\n{_TEXT_END}"
    try:
        current_block = _text_managed_block(existing)
    except ValueError:
        recorder.conflict(path)
        return
    previously_managed = recorder.is_managed(path)
    if current_block is not None:
        if current_block == desired_block:
            recorder.mark_managed(path)
            return
        if not previously_managed:
            recorder.conflict(path)
            return
        if not recorder.managed_unchanged(path):
            recorder.conflict(path)
            return
    elif previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    merged = _merge_marker_text(existing, body)
    if merged is None:
        recorder.conflict(path)
        return
    recorder.write_merged(path, merged)


def _read_json_object(path: Path, recorder: _Recorder) -> Optional[dict[str, Any]]:
    if recorder.unsafe(path):
        recorder.conflict(path)
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        recorder.conflict(path)
        return None
    if not isinstance(value, dict):
        recorder.conflict(path)
        return None
    return value


def _write_json(recorder: _Recorder, path: Path, value: Mapping[str, Any]) -> None:
    recorder.write_merged(
        path,
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )


def _append_unique(values: Any, item: Mapping[str, Any]) -> list[Any]:
    result = list(values) if isinstance(values, list) else []
    if item not in result:
        result.append(dict(item))
    return result


def _runtime_hook_command(
    host: str, event: str, runtime: _RuntimeLayout
) -> str:
    """Build a POSIX hook command that is independent of the session cwd.

    Claude and AGY currently expose only their shell ``command`` field here,
    so those two adapters require a POSIX-compatible shell on Windows. Codex's
    native schema supports a Windows override and receives one below.
    """

    marker = " && ".join(
        f'[ -f "$SOLOMON_ROOT/{relative}" ]' for relative in runtime.marker_paths
    )
    project = f'$SOLOMON_ROOT{runtime.project_subpath}'
    return (
        '{ SOLOMON_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" && '
        f"{marker}; }} || "
        '{ SOLOMON_ROOT="$PWD"; while [ "$SOLOMON_ROOT" != "/" ]; do '
        f"{marker} && break; "
        'SOLOMON_ROOT="$(dirname "$SOLOMON_ROOT")"; done; '
        f"{marker}; }} && "
        'UV_PROJECT_ENVIRONMENT="$SOLOMON_ROOT/.agents/solomon/state/venv" '
        f'uv run --frozen --project "{project}" '
        f"python -m solomon_harness.cli host-hook {event} --host {host}"
    )


def _windows_runtime_hook_command(
    host: str, event: str, runtime: _RuntimeLayout
) -> str:
    """Build Codex's Windows override using cmd's native Git-root lookup.

    Unlike the POSIX launcher, this requires a Git worktree; the native Codex
    override is explicit so the POSIX ancestor-search syntax is never sent to
    ``cmd.exe``.
    """

    project = f"%R{runtime.project_subpath.replace('/', chr(92))}"
    return (
        'for /f "delims=" %R in (\'git rev-parse --show-toplevel\') do '
        'set "UV_PROJECT_ENVIRONMENT=%R\\.agents\\solomon\\state\\venv" && '
        f'uv run --frozen --project "{project}" '
        f"python -m solomon_harness.cli host-hook {event} --host {host}"
    )


def _hook_handler(
    host: str, event: str, runtime: _RuntimeLayout
) -> dict[str, Any]:
    handler: dict[str, Any] = {
        "command": _runtime_hook_command(host, event, runtime),
        "timeout": 30,
        "type": "command",
    }
    if host == "codex":
        handler["commandWindows"] = _windows_runtime_hook_command(
            host, event, runtime
        )
    return handler


def _list_hook_specs(
    host: str, runtime: _RuntimeLayout
) -> dict[str, dict[str, Any]]:
    if host == "claude":
        return {
            "SessionStart": {
                "hooks": [_hook_handler(host, "session-start", runtime)]
            },
            "PreToolUse": {
                "hooks": [_hook_handler(host, "pre-tool-use", runtime)],
                "matcher": "Bash|Edit|Write|MultiEdit|NotebookEdit",
            },
        }
    if host == "codex":
        return {
            "SessionStart": {
                "hooks": [_hook_handler(host, "session-start", runtime)],
                "matcher": "startup|resume|clear|compact",
            },
            "PreToolUse": {
                "hooks": [_hook_handler(host, "pre-tool-use", runtime)],
                "matcher": "^(Bash|apply_patch|Edit|Write)$",
            },
        }
    raise ValueError(f"list-hook host is unsupported: {host}")


def _agy_hook_specs(runtime: _RuntimeLayout) -> dict[str, dict[str, Any]]:
    return {
        "solomon-session-resume": {
            "PreInvocation": [_hook_handler("agy", "pre-invocation", runtime)],
        },
        "solomon-loop-guard": {
            "PreToolUse": [
                {
                    "hooks": [_hook_handler("agy", "pre-tool-use", runtime)],
                    "matcher": (
                        "run_command|write_to_file|replace_file_content|"
                        "multi_replace_file_content"
                    ),
                }
            ]
        },
    }


def _contains_host_hook(value: Any, host: str) -> bool:
    text = json.dumps(value, sort_keys=True)
    return "solomon_harness.cli host-hook" in text and f"--host {host}" in text


def _host_hook_nodes(hooks: Mapping[str, Any], host: str) -> list[tuple[str, Any]]:
    result: list[tuple[str, Any]] = []
    for event, values in hooks.items():
        if not isinstance(values, list):
            continue
        result.extend(
            (event, item) for item in values if _contains_host_hook(item, host)
        )
    return result


def _host_hook_specs_are_exact(
    hooks: Mapping[str, Any], host: str, desired: Mapping[str, Mapping[str, Any]]
) -> bool:
    actual = _host_hook_nodes(hooks, host)
    if len(actual) != len(desired):
        return False
    return all(
        sum(1 for actual_event, node in actual if actual_event == event and node == specification)
        == 1
        for event, specification in desired.items()
    )


def _remove_host_hook_nodes(hooks: dict[str, Any], host: str) -> None:
    for event in list(hooks):
        values = hooks[event]
        if not isinstance(values, list):
            continue
        retained = [item for item in values if not _contains_host_hook(item, host)]
        if retained:
            hooks[event] = retained
        else:
            hooks.pop(event)


def _merge_list_hooks(
    recorder: _Recorder,
    path: Path,
    host: str,
    runtime: _RuntimeLayout,
) -> None:
    document = _read_json_object(path, recorder)
    if document is None:
        return
    hooks = document.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        recorder.conflict(path)
        return
    desired = _list_hook_specs(host, runtime)
    if any(event in hooks and not isinstance(hooks[event], list) for event in desired):
        recorder.conflict(path)
        return

    previously_managed = recorder.is_managed(path)
    host_nodes = _host_hook_nodes(hooks, host)
    exact = _host_hook_specs_are_exact(hooks, host, desired)
    if exact:
        recorder.mark_managed(path)
        return
    if not previously_managed and host_nodes:
        recorder.conflict(path)
        return
    if previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    if previously_managed:
        _remove_host_hook_nodes(hooks, host)
    for event, specification in desired.items():
        hooks[event] = _append_unique(hooks.get(event), specification)
    _write_json(recorder, path, document)


def _merge_claude_settings(
    recorder: _Recorder, path: Path, runtime: _RuntimeLayout
) -> None:
    _merge_list_hooks(recorder, path, "claude", runtime)


def _merge_agy_hooks(
    recorder: _Recorder, path: Path, runtime: _RuntimeLayout
) -> None:
    document = _read_json_object(path, recorder)
    if document is None:
        return
    reserved = _agy_hook_specs(runtime)
    existing_reserved = {key: document[key] for key in reserved if key in document}
    previously_managed = recorder.is_managed(path)
    exact = all(document.get(key) == value for key, value in reserved.items())
    if exact:
        recorder.mark_managed(path)
        return
    if not previously_managed and existing_reserved:
        recorder.conflict(path)
        return
    if previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    document.update(reserved)
    _write_json(recorder, path, document)


def _codex_hooks_toml(runtime: _RuntimeLayout) -> str:
    """Render Codex hooks inline so Git worktrees use the trusted config layer."""

    lines: list[str] = []
    specifications = _list_hook_specs("codex", runtime)
    for event in ("PreToolUse", "SessionStart"):
        specification = specifications[event]
        lines.extend(
            (
                f"[[hooks.{event}]]",
                f"matcher = {_yaml_string(str(specification['matcher']))}",
                "",
            )
        )
        for handler in specification["hooks"]:
            lines.extend(
                (
                    f"[[hooks.{event}.hooks]]",
                    f"type = {_yaml_string(str(handler['type']))}",
                    f"command = {_yaml_string(str(handler['command']))}",
                    f"commandWindows = {_yaml_string(str(handler['commandWindows']))}",
                    f"timeout = {int(handler['timeout'])}",
                    "",
                )
            )
    return "\n".join(lines).rstrip()


def _merge_mcp_json(
    recorder: _Recorder, path: Path, runtime: _RuntimeLayout
) -> None:
    document = _read_json_object(path, recorder)
    if document is None:
        return
    servers = document.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        recorder.conflict(path)
        return
    desired = {
        "args": runtime.mcp_args(),
        "command": _MCP_COMMAND,
        "env": runtime.mcp_env(),
    }
    previously_managed = recorder.is_managed(path)
    if "solomon-memory" in servers:
        existing = servers["solomon-memory"]
        if existing == desired:
            recorder.mark_managed(path)
            return
        if not previously_managed or not recorder.managed_unchanged(path):
            recorder.conflict(path)
            return
    elif previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    servers["solomon-memory"] = desired
    _write_json(recorder, path, document)


def _merge_toml_marker(existing: str, body: str) -> Optional[str]:
    block = f"{_TOML_START}\n{body.rstrip()}\n{_TOML_END}"
    start_count = existing.count(_TOML_START)
    end_count = existing.count(_TOML_END)
    if start_count != end_count or start_count > 1:
        return None
    if start_count:
        before, remainder = existing.split(_TOML_START, 1)
        _, after = remainder.split(_TOML_END, 1)
        prefix = before.rstrip()
        return (prefix + "\n\n" if prefix else "") + block + after
    if re.search(r"(?m)^\s*\[\s*mcp_servers\.solomon-memory\s*]\s*$", existing):
        return None
    if existing.strip():
        return existing.rstrip() + "\n\n" + block + "\n"
    return block + "\n"


def _toml_managed_block(existing: str) -> Optional[str]:
    start_count = existing.count(_TOML_START)
    end_count = existing.count(_TOML_END)
    if start_count != end_count or start_count > 1:
        raise ValueError("invalid Solomon TOML markers")
    if not start_count:
        return None
    _, remainder = existing.split(_TOML_START, 1)
    managed, _ = remainder.split(_TOML_END, 1)
    return f"{_TOML_START}{managed}{_TOML_END}"


def _codex_contains_solomon_hook(document: Mapping[str, Any]) -> bool:
    hooks = document.get("hooks")
    if not isinstance(hooks, Mapping):
        return False
    return any(
        _contains_host_hook(specification, "codex")
        for specifications in hooks.values()
        if isinstance(specifications, list)
        for specification in specifications
    )


def _merge_codex_config(
    recorder: _Recorder, path: Path, runtime: _RuntimeLayout
) -> None:
    if recorder.unsafe(path):
        recorder.conflict(path)
        return
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = ""
    except (OSError, UnicodeDecodeError):
        recorder.conflict(path)
        return
    required = _runtime_project_is_valid(recorder.root, runtime)
    body = (
        _codex_hooks_toml(runtime)
        + "\n\n"
        "[mcp_servers.solomon-memory]\n"
        f"command = {_yaml_string(_MCP_COMMAND)}\n"
        f"args = {json.dumps(runtime.mcp_args(), ensure_ascii=False)}\n"
        f"required = {str(required).lower()}\n"
        "startup_timeout_sec = 10\n"
        "tool_timeout_sec = 60\n"
        "env = { UV_PROJECT_ENVIRONMENT = "
        f"{_yaml_string(runtime.environment_path)} }}"
    )
    desired_block = f"{_TOML_START}\n{body.rstrip()}\n{_TOML_END}"
    try:
        current_block = _toml_managed_block(existing)
    except ValueError:
        recorder.conflict(path)
        return
    try:
        document = tomllib.loads(existing) if existing.strip() else {}
    except tomllib.TOMLDecodeError:
        recorder.conflict(path)
        return
    if current_block is None and _codex_contains_solomon_hook(document):
        recorder.conflict(path)
        return
    previously_managed = recorder.is_managed(path)
    if current_block is not None:
        if current_block == desired_block:
            recorder.mark_managed(path)
            return
        if not previously_managed:
            recorder.conflict(path)
            return
        if not recorder.managed_unchanged(path):
            recorder.conflict(path)
            return
    elif previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    merged = _merge_toml_marker(existing, body)
    if merged is None:
        recorder.conflict(path)
        return
    recorder.write_merged(path, merged)


def compile_adapters(project_root: os.PathLike[str] | str) -> AdapterCompileResult:
    """Render native adapters from an installed or Git-proven source catalog.

    Whole-file bridges are overwritten only when absent, already byte-identical,
    or unchanged from the previous ownership manifest. Shared JSON/TOML and
    instruction files receive namespaced semantic/marker merges, preserving
    unrelated host configuration.
    """

    from solomon_harness.layout import HarnessPaths

    root = Path(project_root).resolve()
    paths = HarnessPaths(root)
    specialists, workflows, rules = _catalog(root)
    recorder = _Recorder(root, _load_previous_ownership(root))
    runtime = _runtime_layout(recorder._is_source_checkout())

    _write_marker_file(
        recorder,
        paths.root_instructions,
        (
            f"The Solomon rules are in `{_reference(root, rules)}`. "
            "Read that file completely before starting work."
        ),
    )
    _write_marker_file(
        recorder,
        paths.claude_instructions,
        f"@../{_reference(root, rules)}",
    )

    for specialist in specialists:
        markdown = _specialist_markdown(specialist, root=root, rules=rules)
        recorder.write_generated(paths.claude_agents / f"{specialist.name}.md", markdown)
        recorder.write_generated(
            paths.agents_root / "agents" / specialist.name / "agent.md",
            markdown,
        )
        recorder.write_generated(
            paths.codex_agents / f"{specialist.name}.toml",
            _specialist_toml(specialist, root=root, rules=rules),
        )

    for workflow in workflows:
        content = _workflow_skill(workflow, root)
        claude_content = _workflow_skill(
            workflow,
            root,
            allowed_tools=_claude_allowed_tools(workflow, root),
        )
        directory = f"solomon-{workflow.name}"
        recorder.write_generated(paths.shared_skills / directory / "SKILL.md", content)
        recorder.write_generated(
            paths.claude_skills / directory / "SKILL.md",
            claude_content,
        )

    _merge_claude_settings(recorder, paths.claude_settings, runtime)
    _merge_agy_hooks(recorder, paths.agy_hooks, runtime)
    _merge_mcp_json(recorder, paths.claude_mcp, runtime)
    _merge_mcp_json(recorder, paths.agy_mcp, runtime)
    _merge_codex_config(recorder, paths.codex_config, runtime)

    plugin = {
        "description": (
            "Host adapter for the Solomon project harness. " + _GENERATED_MARKER
        ),
        "name": "solomon",
        "version": "1.0.0",
    }
    recorder.write_generated(
        paths.agy_plugins / "plugin.json",
        json.dumps(plugin, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )
    return recorder.result()


def _read_text(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def _valid_generated_text(path: Path, *required: str) -> bool:
    text = _read_text(path)
    return bool(
        text is not None
        and _GENERATED_MARKER in text
        and all(fragment in text for fragment in required)
    )


def _specialist_names(
    directory: Path, host: str, agents_reference: str
) -> tuple[str, ...]:
    if not directory.is_dir():
        return ()
    result: list[str] = []
    if host == "agy":
        candidates = sorted(directory.iterdir())
        for candidate in candidates:
            path = candidate / "agent.md"
            if candidate.is_dir() and _valid_generated_text(
                path, f"{agents_reference}/{candidate.name}"
            ):
                result.append(candidate.name)
        return tuple(result)
    if host == "claude":
        candidates = sorted(directory.glob("*.md"))
        for path in candidates:
            if _valid_generated_text(
                path, f"{agents_reference}/{path.stem}"
            ):
                result.append(path.stem)
        return tuple(result)
    if host == "codex":
        candidates = sorted(directory.glob("*.toml"))
        for path in candidates:
            text = _read_text(path)
            if text is None or _GENERATED_MARKER not in text:
                continue
            try:
                document = tomllib.loads(text)
            except tomllib.TOMLDecodeError:
                continue
            if (
                document.get("name") == path.stem
                and f"{agents_reference}/{path.stem}"
                in str(document.get("developer_instructions", ""))
            ):
                result.append(path.stem)
        return tuple(result)
    raise ValueError(f"unknown specialist host: {host}")


def _skill_names(
    directory: Path, workflow_references: Mapping[str, str]
) -> tuple[str, ...]:
    if not directory.is_dir():
        return ()
    return tuple(
        sorted(
            child.name.removeprefix("solomon-")
            for child in directory.iterdir()
            if child.is_dir()
            and child.name.startswith("solomon-")
            and child.name.removeprefix("solomon-") in workflow_references
            and _valid_generated_text(
                child / "SKILL.md",
                workflow_references[child.name.removeprefix("solomon-")],
            )
        )
    )


def _read_json(path: Path) -> Optional[dict[str, Any]]:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    return document if isinstance(document, dict) else None


def _valid_hooks(
    path: Path, host: str, runtime: _RuntimeLayout
) -> bool:
    document = _read_json(path)
    if document is None:
        return False
    if host == "agy":
        desired = _agy_hook_specs(runtime)
        return all(document.get(key) == value for key, value in desired.items())
    hooks = document.get("hooks")
    return bool(
        isinstance(hooks, dict)
        and _host_hook_specs_are_exact(
            hooks, host, _list_hook_specs(host, runtime)
        )
    )


def _valid_json_mcp(
    path: Path, root: Path, runtime: _RuntimeLayout
) -> bool:
    document = _read_json(path)
    if document is None:
        return False
    servers = document.get("mcpServers")
    desired = {
        "args": runtime.mcp_args(),
        "command": _MCP_COMMAND,
        "env": runtime.mcp_env(),
    }
    return bool(
        _runtime_project_is_valid(root, runtime)
        and isinstance(servers, dict)
        and servers.get("solomon-memory") == desired
    )


def _read_toml(path: Path) -> Optional[dict[str, Any]]:
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError):
        return None
    return document if isinstance(document, dict) else None


def _valid_codex_mcp(
    document: Optional[Mapping[str, Any]],
    root: Path,
    runtime: _RuntimeLayout,
) -> bool:
    if document is None:
        return False
    servers = document.get("mcp_servers")
    if not isinstance(servers, Mapping):
        return False
    server = servers.get("solomon-memory")
    if not isinstance(server, Mapping):
        return False
    return bool(
        _runtime_project_is_valid(root, runtime)
        and server.get("command") == _MCP_COMMAND
        and server.get("args") == runtime.mcp_args()
        and server.get("env") == runtime.mcp_env()
        and server.get("required") is True
    )


def _valid_codex_hooks(
    document: Optional[Mapping[str, Any]], runtime: _RuntimeLayout
) -> bool:
    if document is None:
        return False
    hooks = document.get("hooks")
    if not isinstance(hooks, Mapping):
        return False
    for event, specification in _list_hook_specs("codex", runtime).items():
        configured = hooks.get(event)
        if not isinstance(configured, list) or specification not in configured:
            return False
    return True


def _instruction_is_valid(
    path: Path, host: str, rules_reference: str
) -> bool:
    text = _read_text(path)
    if text is None or _TEXT_START not in text or _TEXT_END not in text:
        return False
    if host == "claude":
        return f"@../{rules_reference}" in text
    return rules_reference in text


def _overall_status(states: Mapping[str, str]) -> str:
    configured = {state for state in states.values() if state != "unavailable"}
    if "pending_trust" in configured:
        return "pending_trust"
    if "configured" in configured:
        return "configured"
    return "active" if configured else "unavailable"


def inspect_capabilities(project_root: os.PathLike[str] | str) -> dict[str, dict[str, Any]]:
    """Inspect semantic configuration and activation state for each host.

    ``capabilities`` remains the backwards-compatible set of configured
    capabilities. ``capability_states`` separates immediately active discovery
    surfaces from native configuration and Codex configuration awaiting trust.
    Static repository inspection cannot prove that a user trusted a particular
    Codex hook hash, so it never reports those hooks as active.
    """

    from solomon_harness.layout import HarnessPaths

    root = Path(project_root).resolve()
    paths = HarnessPaths(root)
    try:
        canonical_specialists, canonical_workflows, canonical_rules = _catalog(root)
    except FileNotFoundError:
        canonical_specialists = []
        canonical_workflows = []
        canonical_rules = paths.rules
    recorder = _Recorder(root, {})
    runtime = _runtime_layout(recorder._is_source_checkout())
    expected_specialists = tuple(sorted(item.name for item in canonical_specialists))
    expected_workflows = tuple(sorted(item.name for item in canonical_workflows))
    agents_reference = _reference(root, paths.resolve_agents())
    rules_reference = _reference(root, canonical_rules)
    workflow_references = {
        item.name: _reference(root, item.source) for item in canonical_workflows
    }
    shared_workflows = _skill_names(paths.shared_skills, workflow_references)
    host_specialists = {
        "agy": _specialist_names(
            paths.agents_root / "agents", "agy", agents_reference
        ),
        "claude": _specialist_names(
            paths.claude_agents, "claude", agents_reference
        ),
        "codex": _specialist_names(
            paths.codex_agents, "codex", agents_reference
        ),
    }
    host_workflows = {
        "agy": shared_workflows,
        "claude": _skill_names(paths.claude_skills, workflow_references),
        "codex": shared_workflows,
    }
    codex_config = _read_toml(paths.codex_config)
    codex_features = codex_config.get("features", {}) if codex_config else {}
    codex_hooks_disabled = bool(
        isinstance(codex_features, Mapping)
        and codex_features.get("hooks", codex_features.get("codex_hooks", True)) is False
    )

    result: dict[str, dict[str, Any]] = {}
    for host in HOSTS:
        states = {capability: "unavailable" for capability in CAPABILITIES}
        states["headless"] = "active"

        instruction_path = (
            paths.claude_instructions if host == "claude" else paths.root_instructions
        )
        if _instruction_is_valid(instruction_path, host, rules_reference):
            states["instructions"] = "active"
        if expected_specialists and host_specialists[host] == expected_specialists:
            states["specialists"] = "pending_trust" if host == "codex" else "active"
        if expected_workflows and host_workflows[host] == expected_workflows:
            states["workflows"] = "active"

        hooks_valid = (
            _valid_codex_hooks(codex_config, runtime)
            if host == "codex"
            else _valid_hooks(
                {
                    "agy": paths.agy_hooks,
                    "claude": paths.claude_settings,
                }[host],
                host,
                runtime,
            )
        )
        if hooks_valid:
            hook_state = "configured"
            if host == "codex" and not codex_hooks_disabled:
                hook_state = "pending_trust"
            states["session_start"] = hook_state
            states["pre_tool_guard"] = hook_state

        mcp_valid = {
            "agy": lambda: _valid_json_mcp(paths.agy_mcp, root, runtime),
            "claude": lambda: _valid_json_mcp(paths.claude_mcp, root, runtime),
            "codex": lambda: _valid_codex_mcp(codex_config, root, runtime),
        }[host]()
        if mcp_valid:
            states["mcp"] = "pending_trust" if host == "codex" else "configured"

        if not set(states.values()) <= _CAPABILITY_STATES:
            raise AssertionError("unknown capability activation state")
        capabilities = {
            capability for capability, state in states.items() if state != "unavailable"
        }
        result[host] = {
            "capabilities": capabilities,
            "capability_states": states,
            "status": _overall_status(states),
            "specialists": host_specialists[host],
            "workflows": host_workflows[host],
        }
    return result
