"""AGY-native rendering, merge, and capability inspection adapter."""

import json
from typing import Any

from solomon_harness.host_adapter_common import (
    CAPABILITIES,
    HostCompileContext,
    HostInspectionContext,
    _hook_handler,
    _instruction_is_valid,
    _merge_mcp_json,
    _read_json_object,
    _specialist_markdown,
    _specialist_names,
    _valid_hooks,
    _valid_json_mcp,
    _write_json,
)
from solomon_harness.host_adapter_contract import HostInspection


def _hook_specs(context: HostCompileContext | HostInspectionContext) -> dict[str, dict[str, Any]]:
    return {
        "solomon-session-resume": {
            "PreInvocation": [_hook_handler("agy", "pre-invocation", context.runtime)],
        },
        "solomon-loop-guard": {
            "PreToolUse": [
                {
                    "hooks": [_hook_handler("agy", "pre-tool-use", context.runtime)],
                    "matcher": (
                        "run_command|write_to_file|replace_file_content|"
                        "multi_replace_file_content"
                    ),
                }
            ]
        },
    }


def _merge_hooks(context: HostCompileContext) -> None:
    path = context.paths.agy_hooks
    document = _read_json_object(path, context.recorder)
    if document is None:
        return
    reserved = _hook_specs(context)
    existing_reserved = {key: document[key] for key in reserved if key in document}
    previously_managed = context.recorder.is_managed(path)
    exact = all(document.get(key) == value for key, value in reserved.items())
    if exact:
        context.recorder.mark_managed(path)
        return
    if not previously_managed and existing_reserved:
        context.recorder.conflict(path)
        return
    if previously_managed and not context.recorder.managed_unchanged(path):
        context.recorder.conflict(path)
        return
    document.update(reserved)
    _write_json(context.recorder, path, document)


class AgyAdapter:
    """Native AGY adapter behind the shared host port."""

    name = "agy"

    def compile(self, context: HostCompileContext) -> None:
        if not isinstance(context, HostCompileContext):
            raise TypeError("AGY compile context is invalid")

        for specialist in context.specialists:
            context.recorder.write_generated(
                context.paths.agents_root / "agents" / specialist.name / "agent.md",
                _specialist_markdown(
                    specialist,
                    root=context.root,
                    rules=context.rules,
                ),
            )
        _merge_hooks(context)
        _merge_mcp_json(
            context.recorder,
            context.paths.agy_mcp,
            context.runtime,
            context.mcp_command,
        )
        plugin = {
            "description": (
                "Host adapter for the Solomon project harness. "
                "Generated by solomon-harness; edit the source under .agents/solomon."
            ),
            "name": "solomon",
            "version": "1.0.0",
        }
        context.recorder.write_generated(
            context.paths.agy_plugins / "plugin.json",
            json.dumps(plugin, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        )

    def inspect(self, context: HostInspectionContext) -> HostInspection:
        if not isinstance(context, HostInspectionContext):
            raise TypeError("AGY inspection context is invalid")

        specialists = _specialist_names(
            context.paths.agents_root / "agents",
            self.name,
            context.agents_reference,
        )
        workflows = context.shared_workflows
        states = {capability: "unavailable" for capability in CAPABILITIES}
        states["headless"] = "active"
        if _instruction_is_valid(
            context.paths.root_instructions,
            self.name,
            context.rules_reference,
        ):
            states["instructions"] = "active"
        if context.expected_specialists and specialists == context.expected_specialists:
            states["specialists"] = "active"
        if context.expected_workflows and workflows == context.expected_workflows:
            states["workflows"] = "active"
        if _valid_hooks(context.paths.agy_hooks, self.name, _hook_specs(context)):
            states["session_start"] = "configured"
            states["pre_tool_guard"] = "configured"
        if _valid_json_mcp(
            context.paths.agy_mcp,
            context.root,
            context.runtime,
            context.mcp_command,
        ):
            states["mcp"] = "configured"
        return HostInspection(states, specialists, workflows)


ADAPTER = AgyAdapter()
