"""Codex-native rendering, merge, and capability inspection adapter."""

import json
import tomllib
from typing import Any, Mapping, Optional

from solomon_harness.host_adapter_common import (
    CAPABILITIES,
    HostCompileContext,
    HostInspectionContext,
    _contains_host_hook,
    _hook_handler,
    _instruction_is_valid,
    _merge_toml_marker,
    _read_toml,
    _Specialist,
    _runtime_project_is_valid,
    _specialist_names,
    _toml_managed_block,
    _yaml_string,
)
from solomon_harness.host_adapter_contract import HostInspection


def _hook_specs(context: HostCompileContext | HostInspectionContext) -> dict[str, dict[str, Any]]:
    return {
        "SessionStart": {
            "hooks": [_hook_handler("codex", "session-start", context.runtime)],
            "matcher": "startup|resume|clear|compact",
        },
        "PreToolUse": {
            "hooks": [_hook_handler("codex", "pre-tool-use", context.runtime)],
            "matcher": "^(Bash|apply_patch|Edit|Write)$",
        },
    }


def _specialist_toml(
    specialist: _Specialist, context: HostCompileContext
) -> str:
    directory = specialist.directory.relative_to(context.root).as_posix()
    rule_path = context.rules.relative_to(context.root).as_posix()
    instructions = (
        f"Read `{rule_path}`, `{directory}/persona.md`, "
        f"`{directory}/agents/{specialist.name}.md`, and the relevant files in "
        f"`{directory}/skills/` before acting. Follow those canonical instructions."
    )
    marker = "Generated by solomon-harness; edit the source under .agents/solomon."
    return (
        f"# {marker}\n"
        f"name = {_yaml_string(specialist.name)}\n"
        f"description = {_yaml_string(specialist.description)}\n"
        f"developer_instructions = {_yaml_string(instructions)}\n"
    )


def _hooks_toml(context: HostCompileContext) -> str:
    lines: list[str] = []
    specifications = _hook_specs(context)
    for event in ("PreToolUse", "SessionStart"):
        specification = specifications[event]
        lines.extend(
            (
                f"[[hooks.{event}]]",
                f"matcher = {_yaml_string(str(specification['matcher']))}",
                "",
            )
        )
        for handler in specification["hooks"]:
            lines.extend(
                (
                    f"[[hooks.{event}.hooks]]",
                    f"type = {_yaml_string(str(handler['type']))}",
                    f"command = {_yaml_string(str(handler['command']))}",
                    f"commandWindows = {_yaml_string(str(handler['commandWindows']))}",
                    f"timeout = {int(handler['timeout'])}",
                    "",
                )
            )
    return "\n".join(lines).rstrip()


def _contains_managed_hook(document: Mapping[str, Any]) -> bool:
    hooks = document.get("hooks")
    if not isinstance(hooks, Mapping):
        return False
    return any(
        _contains_host_hook(specification, "codex")
        for specifications in hooks.values()
        if isinstance(specifications, list)
        for specification in specifications
    )


def _merge_config(context: HostCompileContext) -> None:
    path = context.paths.codex_config
    recorder = context.recorder
    if recorder.unsafe(path):
        recorder.conflict(path)
        return
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = ""
    except (OSError, UnicodeDecodeError):
        recorder.conflict(path)
        return
    required = _runtime_project_is_valid(context.root, context.runtime)
    body = (
        _hooks_toml(context)
        + "\n\n"
        "[mcp_servers.solomon-memory]\n"
        f"command = {_yaml_string(context.mcp_command)}\n"
        f"args = {json.dumps(context.runtime.mcp_args(), ensure_ascii=False)}\n"
        'cwd = ".."\n'
        f"required = {str(required).lower()}\n"
        "startup_timeout_sec = 10\n"
        "tool_timeout_sec = 60\n"
        "env = { UV_PROJECT_ENVIRONMENT = "
        f"{_yaml_string(context.runtime.environment_path)} }}"
    )
    start = "# >>> solomon-harness managed adapter >>>"
    end = "# <<< solomon-harness managed adapter <<<"
    desired_block = f"{start}\n{body.rstrip()}\n{end}"
    try:
        current_block = _toml_managed_block(existing)
    except ValueError:
        recorder.conflict(path)
        return
    try:
        document = tomllib.loads(existing) if existing.strip() else {}
    except tomllib.TOMLDecodeError:
        recorder.conflict(path)
        return
    if current_block is None and _contains_managed_hook(document):
        recorder.conflict(path)
        return
    previously_managed = recorder.is_managed(path)
    if current_block is not None:
        if current_block == desired_block:
            recorder.mark_managed(path)
            return
        if not previously_managed or not recorder.managed_unchanged(path):
            recorder.conflict(path)
            return
    elif previously_managed and not recorder.managed_unchanged(path):
        recorder.conflict(path)
        return
    merged = _merge_toml_marker(existing, body)
    if merged is None:
        recorder.conflict(path)
        return
    recorder.write_merged(path, merged)


def _valid_mcp(
    document: Optional[Mapping[str, Any]], context: HostInspectionContext
) -> bool:
    if document is None:
        return False
    servers = document.get("mcp_servers")
    if not isinstance(servers, Mapping):
        return False
    server = servers.get("solomon-memory")
    if not isinstance(server, Mapping):
        return False
    return bool(
        _runtime_project_is_valid(context.root, context.runtime)
        and server.get("command") == context.mcp_command
        and server.get("args") == context.runtime.mcp_args()
        and server.get("cwd") == ".."
        and server.get("env") == context.runtime.mcp_env()
        and server.get("required") is True
    )


def _valid_hooks(
    document: Optional[Mapping[str, Any]], context: HostInspectionContext
) -> bool:
    if document is None:
        return False
    hooks = document.get("hooks")
    if not isinstance(hooks, Mapping):
        return False
    for event, specification in _hook_specs(context).items():
        configured = hooks.get(event)
        if not isinstance(configured, list) or specification not in configured:
            return False
    return True


class CodexAdapter:
    """Native Codex adapter behind the shared host port."""

    name = "codex"

    def compile(self, context: HostCompileContext) -> None:
        if not isinstance(context, HostCompileContext):
            raise TypeError("Codex compile context is invalid")

        for specialist in context.specialists:
            context.recorder.write_generated(
                context.paths.codex_agents / f"{specialist.name}.toml",
                _specialist_toml(specialist, context),
            )
        _merge_config(context)

    def inspect(self, context: HostInspectionContext) -> HostInspection:
        if not isinstance(context, HostInspectionContext):
            raise TypeError("Codex inspection context is invalid")

        specialists = _specialist_names(
            context.paths.codex_agents,
            self.name,
            context.agents_reference,
        )
        workflows = context.shared_workflows
        document = _read_toml(context.paths.codex_config)
        features = document.get("features", {}) if document else {}
        hooks_disabled = bool(
            isinstance(features, Mapping)
            and features.get("hooks", features.get("codex_hooks", True)) is False
        )
        states = {capability: "unavailable" for capability in CAPABILITIES}
        states["headless"] = "active"
        if _instruction_is_valid(
            context.paths.root_instructions,
            self.name,
            context.rules_reference,
        ):
            states["instructions"] = "active"
        if context.expected_specialists and specialists == context.expected_specialists:
            states["specialists"] = "pending_trust"
        if context.expected_workflows and workflows == context.expected_workflows:
            states["workflows"] = "active"
        if _valid_hooks(document, context):
            hook_state = "disabled" if hooks_disabled else "pending_trust"
            states["session_start"] = hook_state
            states["pre_tool_guard"] = hook_state
        if _valid_mcp(document, context):
            states["mcp"] = "pending_trust"
        return HostInspection(states, specialists, workflows)


ADAPTER = CodexAdapter()
