"""Compile canonical project agents into host-tool wrappers safely."""

import os
import re
import stat
from typing import List, Optional, Set

from solomon_harness.secure_paths import (
    UnsafePathError,
    atomic_replace_at,
    open_directory_at,
    open_regular_at,
    open_root_directory,
    read_regular_at,
    stat_at,
    unlink_at,
)

MAX_ROLE_BYTES = 64 * 1024
MAX_ROLE_LINE_CHARS = 2048
MAX_WRAPPER_BYTES = 64 * 1024
AGENT_NAME_PATTERN = re.compile(r"^[a-z0-9_]+$")
SOLOMON_WRAPPER_MARKERS = (
    b"This file is generated by `solomon-harness compile`.",
    b"This file is generated by scripts/generate-integrations.py.",
)


def _close(descriptor: Optional[int]) -> None:
    if descriptor is not None:
        os.close(descriptor)


def _discover_agents_at(agents_fd: int, *, strict: bool = False) -> List[str]:
    names = []
    for item in sorted(os.listdir(agents_fd)):
        if not AGENT_NAME_PATTERN.fullmatch(item):
            continue
        agent_fd = role_dir_fd = role_fd = persona_fd = skills_fd = None
        try:
            agent_fd = open_directory_at(agents_fd, item)
            assert agent_fd is not None
            role_dir_fd = open_directory_at(agent_fd, "agents")
            assert role_dir_fd is not None
            role_fd = open_regular_at(
                role_dir_fd,
                f"{item}.md",
                max_bytes=MAX_ROLE_BYTES,
            )
            persona_fd = open_regular_at(agent_fd, "persona.md")
            skills_fd = open_directory_at(agent_fd, "skills")
            names.append(item)
        except (FileNotFoundError, UnsafePathError, OSError) as exc:
            if strict:
                raise UnsafePathError(f"unsafe agent catalog entry: {item}") from exc
            continue
        finally:
            _close(skills_fd)
            _close(persona_fd)
            _close(role_fd)
            _close(role_dir_fd)
            _close(agent_fd)
    return names


def discover_agents(agents_dir: str, *, strict: bool = False) -> List[str]:
    """Return complete canonical agents without following catalog symlinks."""
    try:
        agents_fd = open_root_directory(agents_dir)
    except (FileNotFoundError, UnsafePathError, OSError):
        if strict:
            raise
        return []
    try:
        return _discover_agents_at(agents_fd, strict=strict)
    finally:
        os.close(agents_fd)


def role_description_from_text(
    text: str,
    agent_name: str,
    *,
    fallback: Optional[str] = None,
) -> str:
    """Extract the role one-liner and delegation cue from bounded role text."""
    fallback = fallback or f"The {agent_name} specialist for this project."
    lines = text.splitlines()
    if any(len(line) > MAX_ROLE_LINE_CHARS for line in lines):
        return fallback

    one_liner = ""
    cue = ""
    in_cue = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            in_cue = stripped.lower() == "## delegation cue"
            continue
        if not stripped or stripped.startswith("#"):
            continue
        if in_cue:
            cue = stripped
            break
        if not one_liner:
            one_liner = stripped
    if one_liner and cue:
        return f"{one_liner} {cue}"
    return one_liner or fallback


def _read_role_at(agents_fd: int, agent_name: str, *, max_bytes: int) -> bytes:
    agent_fd = role_dir_fd = None
    try:
        agent_fd = open_directory_at(agents_fd, agent_name)
        assert agent_fd is not None
        role_dir_fd = open_directory_at(agent_fd, "agents")
        assert role_dir_fd is not None
        return read_regular_at(
            role_dir_fd,
            f"{agent_name}.md",
            max_bytes=max_bytes,
        )
    finally:
        _close(role_dir_fd)
        _close(agent_fd)


def read_agent_role(agents_dir: str, agent_name: str, *, max_bytes: int) -> bytes:
    """Read one canonical agent role through anchored directory descriptors."""
    if not AGENT_NAME_PATTERN.fullmatch(agent_name):
        raise UnsafePathError(f"unsafe agent name: {agent_name!r}")
    agents_fd = open_root_directory(agents_dir)
    try:
        return _read_role_at(agents_fd, agent_name, max_bytes=max_bytes)
    finally:
        os.close(agents_fd)


def _role_description_at(agents_fd: int, agent_name: str) -> str:
    fallback = f"The {agent_name} specialist for this project."
    try:
        content = _read_role_at(agents_fd, agent_name, max_bytes=MAX_ROLE_BYTES)
        return role_description_from_text(content.decode("utf-8"), agent_name)
    except (FileNotFoundError, UnsafePathError, UnicodeDecodeError, OSError):
        return fallback


def role_description(role_path: str, agent_name: str, agents_dir: str) -> str:
    """Read a canonical role through an agents-directory descriptor."""
    fallback = f"The {agent_name} specialist for this project."
    expected = os.path.join(agent_name, "agents", f"{agent_name}.md")
    try:
        relative = os.path.normpath(os.path.relpath(role_path, agents_dir))
    except ValueError:
        return fallback
    if relative != expected:
        return fallback
    try:
        agents_fd = open_root_directory(agents_dir)
    except (FileNotFoundError, UnsafePathError, OSError):
        return fallback
    try:
        return _role_description_at(agents_fd, agent_name)
    finally:
        os.close(agents_fd)


def _yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _format_path(path: str, quote_paths: bool) -> str:
    return f"`{path}`" if quote_paths else path


def _render_subagent(
    agent_name: str,
    description: str,
    trust_root: str,
    *,
    project_label: str,
    model: Optional[str],
    quote_paths: bool,
    compliance_suffix: str,
    memory_clause: str,
    generator_label: str,
) -> str:
    role = _format_path(f"agents/{agent_name}/agents/{agent_name}.md", quote_paths)
    persona = _format_path(f"agents/{agent_name}/persona.md", quote_paths)
    skills = _format_path(f"agents/{agent_name}/skills/", quote_paths)
    source = _format_path(f"agents/{agent_name}/", quote_paths)
    rules = _format_path(trust_root, quote_paths)
    model_line = f"model: {model}\n" if model else ""
    return (
        "---\n"
        f"name: {agent_name}\n"
        f"description: {_yaml_quote(description)}\n"
        f"{model_line}"
        "---\n\n"
        f"You are the {agent_name} specialist agent for {project_label}.\n\n"
        f"Your role is defined in {role} and your persona in {persona}. Your skills are "
        f"in {skills}. The shared project rules are in {rules}. Read those files first, "
        "then act strictly within them.\n\n"
        f"Always follow {rules}{compliance_suffix}. When relevant, {memory_clause}.\n\n"
        f"This file is generated by {generator_label}. Edit the source under {source}, "
        "not this file.\n"
    )


def subagent_markdown(agent_name: str, description: str, trust_root: str) -> str:
    """Render the capability-only project adapter."""
    return _render_subagent(
        agent_name,
        description,
        trust_root,
        project_label="this project",
        model=None,
        quote_paths=True,
        compliance_suffix="",
        memory_clause=(
            "persist decisions and handoffs through the project's configured memory integration"
        ),
        generator_label="`solomon-harness compile`",
    )


def harness_subagent_markdown(agent_name: str, description: str, trust_root: str) -> str:
    """Render the dogfooded harness adapter while preserving its established output."""
    return _render_subagent(
        agent_name,
        description,
        trust_root,
        project_label="solomon-harness",
        model=None,
        quote_paths=False,
        compliance_suffix=(
            ": strict TDD, SOLID, design contracts, and the humanizer rules "
            "(no emojis, no AI cliches)"
        ),
        memory_clause=(
            f"persist decisions and handoffs to the project memory described in {trust_root}"
        ),
        generator_label="scripts/generate-integrations.py",
    )


def _trust_root_at(workspace_fd: int) -> str:
    agents_fd = rules_fd = None
    try:
        agents_fd = open_directory_at(workspace_fd, "agents", missing_ok=True)
        if agents_fd is not None:
            rules_fd = open_regular_at(agents_fd, "AGENTS.md", missing_ok=True)
            if rules_fd is not None:
                return "agents/AGENTS.md"
    except (UnsafePathError, OSError):
        pass
    finally:
        _close(rules_fd)
        _close(agents_fd)

    rules_fd = None
    try:
        rules_fd = open_regular_at(workspace_fd, "AGENTS.md", missing_ok=True)
        if rules_fd is not None:
            return "AGENTS.md"
    except (UnsafePathError, OSError):
        pass
    finally:
        _close(rules_fd)
    raise FileNotFoundError(
        "cannot compile agents without agents/AGENTS.md or AGENTS.md project instructions"
    )


def _agent_names_at(workspace_fd: int) -> List[str]:
    agents_fd = None
    try:
        agents_fd = open_directory_at(workspace_fd, "agents", missing_ok=True)
        return _discover_agents_at(agents_fd) if agents_fd is not None else []
    except (UnsafePathError, OSError):
        return []
    finally:
        _close(agents_fd)


def _output_directory_at(workspace_fd: int, *, create: bool) -> Optional[int]:
    claude_fd = None
    try:
        claude_fd = open_directory_at(
            workspace_fd,
            ".claude",
            create=create,
            missing_ok=not create,
        )
        if claude_fd is None:
            return None
        return open_directory_at(
            claude_fd,
            "agents",
            create=create,
            missing_ok=not create,
        )
    finally:
        _close(claude_fd)


def _is_solomon_wrapper(output_fd: int, name: str) -> bool:
    try:
        content = read_regular_at(output_fd, name, max_bytes=MAX_WRAPPER_BYTES)
    except (FileNotFoundError, UnsafePathError, OSError):
        return False
    return any(marker in content for marker in SOLOMON_WRAPPER_MARKERS)


def _reconcile_stale_wrappers(output_fd: int, active_agents: Set[str]) -> None:
    for name in sorted(os.listdir(output_fd)):
        if not name.endswith(".md") or name[:-3] in active_agents:
            continue
        if not _is_solomon_wrapper(output_fd, name):
            continue
        current = stat_at(output_fd, name)
        if current is None or not stat.S_ISREG(current.st_mode):
            continue
        unlink_at(output_fd, name)


def generate_claude_agents(workspace_root: str, *, harness_style: bool = False) -> int:
    """Compile and reconcile project agents using directory-FD-anchored writes."""
    workspace_fd = open_root_directory(workspace_root)
    output_fd = agents_fd = None
    try:
        names = _agent_names_at(workspace_fd)
        trust_root = _trust_root_at(workspace_fd) if names else ""
        output_fd = _output_directory_at(workspace_fd, create=bool(names))
        if output_fd is None:
            return 0
        _reconcile_stale_wrappers(output_fd, set(names))
        if not names:
            return 0

        agents_fd = open_directory_at(workspace_fd, "agents")
        assert agents_fd is not None
        renderer = harness_subagent_markdown if harness_style else subagent_markdown
        for name in names:
            description = _role_description_at(agents_fd, name)
            content = renderer(name, description, trust_root).encode("utf-8")
            atomic_replace_at(output_fd, f"{name}.md", content)
    finally:
        _close(agents_fd)
        _close(output_fd)
        os.close(workspace_fd)

    print(f"Generated {len(names)} Claude Code subagents in {workspace_root}/.claude/agents: {', '.join(names)}")
    return len(names)
