"""Compile canonical project agents into host-tool wrappers safely."""

import os
import re
import stat
from typing import Iterable, List, Optional, Set

from solomon_harness.secure_paths import (
    UnsafePathError,
    atomic_replace_at,
    open_directory_at,
    open_regular_at,
    open_root_directory,
    read_regular_at,
    stat_at,
    unlink_at,
)

MAX_ROLE_BYTES = 64 * 1024
MAX_ROLE_LINE_CHARS = 2048
MAX_PERSONA_BYTES = 64 * 1024
MAX_WRAPPER_BYTES = 64 * 1024
MAX_SKILL_FILES = 128
MAX_SKILL_ENTRIES = 256
MAX_SKILL_DEPTH = 8
MAX_SKILL_BYTES = 256 * 1024
MAX_SKILLS_TOTAL_BYTES = 16 * 1024 * 1024
AGENT_NAME_PATTERN = re.compile(r"^[a-z0-9_]+$")
SKILL_FILE_PATTERN = re.compile(r"^[a-z0-9_]+\.md$")
SKILL_PACKAGE_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]*$")
SKILL_COMPONENT_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
ALLOWED_SKILL_EXTENSIONS = frozenset({
    ".md",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".rst",
    ".csv",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
})
SCRIPT_DIRECTORY_NAMES = frozenset({"scripts", "bin", "hooks", ".githooks"})
SOLOMON_WRAPPER_MARKERS = (
    b"This file is generated by `solomon-harness compile`.",
    b"This file is generated by scripts/generate-integrations.py.",
)


def _close(descriptor: Optional[int]) -> None:
    if descriptor is not None:
        os.close(descriptor)


class _SkillBudget:
    def __init__(self) -> None:
        self.entries = 0
        self.files = 0
        self.total_bytes = 0


def _validate_skill_directory_at(
    directory_fd: int,
    *,
    depth: int,
    package_root: bool,
    budget: _SkillBudget,
) -> None:
    manifest_found = False
    with os.scandir(directory_fd) as entries:
        for entry in entries:
            budget.entries += 1
            if budget.entries > MAX_SKILL_ENTRIES:
                raise UnsafePathError("skills tree has too many entries")
            if not SKILL_COMPONENT_PATTERN.fullmatch(entry.name):
                raise UnsafePathError(f"unsafe skill entry: {entry.name}")

            current = stat_at(directory_fd, entry.name)
            if current is None:
                raise UnsafePathError(f"skill entry disappeared: {entry.name}")
            if stat.S_ISDIR(current.st_mode):
                if depth == 0 and not SKILL_PACKAGE_PATTERN.fullmatch(entry.name):
                    raise UnsafePathError(f"unsafe skill package: {entry.name}")
                if entry.name in SCRIPT_DIRECTORY_NAMES or depth >= MAX_SKILL_DEPTH:
                    raise UnsafePathError(f"unsafe skill directory: {entry.name}")
                child_fd = None
                try:
                    child_fd = open_directory_at(directory_fd, entry.name)
                    assert child_fd is not None
                    _validate_skill_directory_at(
                        child_fd,
                        depth=depth + 1,
                        package_root=depth == 0,
                        budget=budget,
                    )
                finally:
                    _close(child_fd)
                continue

            if not stat.S_ISREG(current.st_mode):
                raise UnsafePathError(f"unsafe skill entry: {entry.name}")
            if depth == 0:
                if not SKILL_FILE_PATTERN.fullmatch(entry.name):
                    raise UnsafePathError(f"unsafe standalone skill: {entry.name}")
            elif os.path.splitext(entry.name)[1].lower() not in ALLOWED_SKILL_EXTENSIONS:
                raise UnsafePathError(f"unsafe packaged skill file: {entry.name}")
            budget.files += 1
            if budget.files > MAX_SKILL_FILES:
                raise UnsafePathError("too many skill files")
            skill_fd = None
            try:
                skill_fd = open_regular_at(directory_fd, entry.name)
                assert skill_fd is not None
                opened_skill = os.fstat(skill_fd)
                if opened_skill.st_mode & 0o111:
                    raise UnsafePathError(f"executable skill file: {entry.name}")
                skill_size = opened_skill.st_size
                if skill_size > MAX_SKILL_BYTES:
                    raise UnsafePathError(f"oversized skill file: {entry.name}")
                budget.total_bytes += skill_size
                if budget.total_bytes > MAX_SKILLS_TOTAL_BYTES:
                    raise UnsafePathError("skills tree exceeds total size limit")
            finally:
                _close(skill_fd)
            if package_root and entry.name == "SKILL.md":
                manifest_found = True

    if package_root and not manifest_found:
        raise UnsafePathError("packaged skill must contain SKILL.md")


def _validate_skills_at(skills_fd: int) -> None:
    """Validate every bounded skill entry through anchored directory descriptors."""
    budget = _SkillBudget()
    _validate_skill_directory_at(
        skills_fd,
        depth=0,
        package_root=False,
        budget=budget,
    )
    if budget.files == 0:
        raise UnsafePathError("skills directory must contain at least one skill")


def _discover_agents_at(agents_fd: int, *, strict: bool = False) -> List[str]:
    names = []
    for item in sorted(os.listdir(agents_fd)):
        if not AGENT_NAME_PATTERN.fullmatch(item):
            continue
        agent_fd = role_dir_fd = role_fd = persona_fd = skills_fd = None
        try:
            agent_fd = open_directory_at(agents_fd, item)
            assert agent_fd is not None
            role_dir_fd = open_directory_at(agent_fd, "agents")
            assert role_dir_fd is not None
            role_fd = open_regular_at(
                role_dir_fd,
                f"{item}.md",
                max_bytes=MAX_ROLE_BYTES,
            )
            persona_fd = open_regular_at(
                agent_fd,
                "persona.md",
                max_bytes=MAX_PERSONA_BYTES,
            )
            skills_fd = open_directory_at(agent_fd, "skills")
            assert skills_fd is not None
            _validate_skills_at(skills_fd)
            names.append(item)
        except (FileNotFoundError, UnsafePathError, OSError) as exc:
            if strict:
                raise UnsafePathError(f"unsafe agent catalog entry: {item}") from exc
            continue
        finally:
            _close(skills_fd)
            _close(persona_fd)
            _close(role_fd)
            _close(role_dir_fd)
            _close(agent_fd)
    return names


def discover_agents(agents_dir: str, *, strict: bool = False) -> List[str]:
    """Return complete canonical agents without following catalog symlinks."""
    try:
        agents_fd = open_root_directory(agents_dir)
    except (FileNotFoundError, UnsafePathError, OSError):
        if strict:
            raise
        return []
    try:
        return _discover_agents_at(agents_fd, strict=strict)
    finally:
        os.close(agents_fd)


def role_description_from_text(
    text: str,
    agent_name: str,
    *,
    fallback: Optional[str] = None,
) -> str:
    """Extract the role one-liner and delegation cue from bounded role text."""
    fallback = fallback or f"The {agent_name} specialist for this project."
    lines = text.splitlines()
    if any(len(line) > MAX_ROLE_LINE_CHARS for line in lines):
        return fallback

    one_liner = ""
    cue = ""
    in_cue = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            in_cue = stripped.lower() == "## delegation cue"
            continue
        if not stripped or stripped.startswith("#"):
            continue
        if in_cue:
            cue = stripped
            break
        if not one_liner:
            one_liner = stripped
    if one_liner and cue:
        return f"{one_liner} {cue}"
    return one_liner or fallback


def _read_role_at(agents_fd: int, agent_name: str, *, max_bytes: int) -> bytes:
    agent_fd = role_dir_fd = None
    try:
        agent_fd = open_directory_at(agents_fd, agent_name)
        assert agent_fd is not None
        role_dir_fd = open_directory_at(agent_fd, "agents")
        assert role_dir_fd is not None
        return read_regular_at(
            role_dir_fd,
            f"{agent_name}.md",
            max_bytes=max_bytes,
        )
    finally:
        _close(role_dir_fd)
        _close(agent_fd)


def read_agent_role(agents_dir: str, agent_name: str, *, max_bytes: int) -> bytes:
    """Read one canonical agent role through anchored directory descriptors."""
    if not AGENT_NAME_PATTERN.fullmatch(agent_name):
        raise UnsafePathError(f"unsafe agent name: {agent_name!r}")
    agents_fd = open_root_directory(agents_dir)
    try:
        return _read_role_at(agents_fd, agent_name, max_bytes=max_bytes)
    finally:
        os.close(agents_fd)


def _role_description_at(agents_fd: int, agent_name: str) -> str:
    fallback = f"The {agent_name} specialist for this project."
    try:
        content = _read_role_at(agents_fd, agent_name, max_bytes=MAX_ROLE_BYTES)
        return role_description_from_text(content.decode("utf-8"), agent_name)
    except (FileNotFoundError, UnsafePathError, UnicodeDecodeError, OSError):
        return fallback


def role_description(role_path: str, agent_name: str, agents_dir: str) -> str:
    """Read a canonical role through an agents-directory descriptor."""
    fallback = f"The {agent_name} specialist for this project."
    expected = os.path.join(agent_name, "agents", f"{agent_name}.md")
    try:
        relative = os.path.normpath(os.path.relpath(role_path, agents_dir))
    except ValueError:
        return fallback
    if relative != expected:
        return fallback
    try:
        agents_fd = open_root_directory(agents_dir)
    except (FileNotFoundError, UnsafePathError, OSError):
        return fallback
    try:
        return _role_description_at(agents_fd, agent_name)
    finally:
        os.close(agents_fd)


def _yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _format_path(path: str, quote_paths: bool) -> str:
    return f"`{path}`" if quote_paths else path


def _render_subagent(
    agent_name: str,
    description: str,
    trust_root: str,
    *,
    project_label: str,
    model: Optional[str],
    quote_paths: bool,
    compliance_suffix: str,
    memory_clause: str,
    generator_label: str,
) -> str:
    role = _format_path(f"agents/{agent_name}/agents/{agent_name}.md", quote_paths)
    persona = _format_path(f"agents/{agent_name}/persona.md", quote_paths)
    skills = _format_path(f"agents/{agent_name}/skills/", quote_paths)
    source = _format_path(f"agents/{agent_name}/", quote_paths)
    rules = _format_path(trust_root, quote_paths)
    model_line = f"model: {model}\n" if model else ""
    return (
        "---\n"
        f"name: {agent_name}\n"
        f"description: {_yaml_quote(description)}\n"
        f"{model_line}"
        "---\n\n"
        f"You are the {agent_name} specialist agent for {project_label}.\n\n"
        f"Your role is defined in {role} and your persona in {persona}. Your skills are "
        f"in {skills}. The shared project rules are in {rules}. Read those files first, "
        "then act strictly within them.\n\n"
        f"Always follow {rules}{compliance_suffix}. When relevant, {memory_clause}.\n\n"
        f"This file is generated by {generator_label}. Edit the source under {source}, "
        "not this file.\n"
    )


def subagent_markdown(agent_name: str, description: str, trust_root: str) -> str:
    """Render the capability-only project adapter."""
    return _render_subagent(
        agent_name,
        description,
        trust_root,
        project_label="this project",
        model=None,
        quote_paths=True,
        compliance_suffix="",
        memory_clause=(
            "persist decisions and handoffs through the project's configured memory integration"
        ),
        generator_label="`solomon-harness compile`",
    )


def harness_subagent_markdown(agent_name: str, description: str, trust_root: str) -> str:
    """Render the dogfooded harness adapter while preserving its established output."""
    return _render_subagent(
        agent_name,
        description,
        trust_root,
        project_label="solomon-harness",
        model=None,
        quote_paths=False,
        compliance_suffix=(
            ": strict TDD, SOLID, design contracts, and the humanizer rules "
            "(no emojis, no AI cliches)"
        ),
        memory_clause=(
            f"persist decisions and handoffs to the project memory described in {trust_root}"
        ),
        generator_label="scripts/generate-integrations.py",
    )


def _trust_root_at(workspace_fd: int) -> str:
    agents_fd = rules_fd = None
    try:
        agents_fd = open_directory_at(workspace_fd, "agents", missing_ok=True)
        if agents_fd is not None:
            rules_fd = open_regular_at(agents_fd, "AGENTS.md", missing_ok=True)
            if rules_fd is not None:
                return "agents/AGENTS.md"
    except (UnsafePathError, OSError):
        pass
    finally:
        _close(rules_fd)
        _close(agents_fd)

    rules_fd = None
    try:
        rules_fd = open_regular_at(workspace_fd, "AGENTS.md", missing_ok=True)
        if rules_fd is not None:
            return "AGENTS.md"
    except (UnsafePathError, OSError):
        pass
    finally:
        _close(rules_fd)
    raise FileNotFoundError(
        "cannot compile agents without agents/AGENTS.md or AGENTS.md project instructions"
    )


def _agent_names_at(workspace_fd: int) -> List[str]:
    agents_fd = None
    try:
        agents_fd = open_directory_at(workspace_fd, "agents", missing_ok=True)
        return _discover_agents_at(agents_fd) if agents_fd is not None else []
    except (UnsafePathError, OSError):
        return []
    finally:
        _close(agents_fd)


def _output_directory_at(workspace_fd: int, *, create: bool) -> Optional[int]:
    claude_fd = None
    try:
        claude_fd = open_directory_at(
            workspace_fd,
            ".claude",
            create=create,
            missing_ok=not create,
        )
        if claude_fd is None:
            return None
        return open_directory_at(
            claude_fd,
            "agents",
            create=create,
            missing_ok=not create,
        )
    finally:
        _close(claude_fd)


def _is_solomon_wrapper(output_fd: int, name: str) -> bool:
    try:
        content = read_regular_at(output_fd, name, max_bytes=MAX_WRAPPER_BYTES)
    except (FileNotFoundError, UnsafePathError, OSError):
        return False
    return any(marker in content for marker in SOLOMON_WRAPPER_MARKERS)


def _reconcile_stale_wrappers(output_fd: int, active_agents: Set[str]) -> None:
    for name in sorted(os.listdir(output_fd)):
        if not name.endswith(".md") or name[:-3] in active_agents:
            continue
        if not _is_solomon_wrapper(output_fd, name):
            continue
        current = stat_at(output_fd, name)
        if current is None or not stat.S_ISREG(current.st_mode):
            continue
        unlink_at(output_fd, name)


def generate_claude_agents(
    workspace_root: str,
    *,
    harness_style: bool = False,
    allowed_names: Optional[Iterable[str]] = None,
) -> int:
    """Compile and reconcile project agents using directory-FD-anchored writes."""
    workspace_fd = open_root_directory(workspace_root)
    output_fd = agents_fd = None
    try:
        names = _agent_names_at(workspace_fd)
        if allowed_names is not None:
            allowed = set(allowed_names)
            names = [name for name in names if name in allowed]
        if not names:
            output_fd = _output_directory_at(workspace_fd, create=False)
            if output_fd is not None:
                _reconcile_stale_wrappers(output_fd, set())
            return 0

        try:
            trust_root = _trust_root_at(workspace_fd)
        except (FileNotFoundError, UnsafePathError, OSError):
            output_fd = _output_directory_at(workspace_fd, create=False)
            if output_fd is not None:
                _reconcile_stale_wrappers(output_fd, set())
            raise

        output_fd = _output_directory_at(workspace_fd, create=True)
        assert output_fd is not None
        _reconcile_stale_wrappers(output_fd, set(names))

        agents_fd = open_directory_at(workspace_fd, "agents")
        assert agents_fd is not None
        renderer = harness_subagent_markdown if harness_style else subagent_markdown
        for name in names:
            description = _role_description_at(agents_fd, name)
            content = renderer(name, description, trust_root).encode("utf-8")
            atomic_replace_at(output_fd, f"{name}.md", content)
    finally:
        _close(agents_fd)
        _close(output_fd)
        os.close(workspace_fd)

    print(f"Generated {len(names)} Claude Code subagents in {workspace_root}/.claude/agents: {', '.join(names)}")
    return len(names)
